import {Categorie} from './categorie.model';

export class Equipe {
  code!: string;
  label!: string;
  codePays!: string;
  url!: string;
  categorie!: Categorie;

  constructor(data = {}) {
    Object.assign(this, data);
  }
}

export const URL_PAYER_INCONNU = 'https://www.gstatic.com/images/branding/product/2x/avatar_anonymous_48dp.png';

export const CLUBS_BASKETBALL: any = {
  LAKERS_LOS_ANGELES: new Equipe({ code: 'LAKERS_LOS_ANGELES', label: 'Lakers de Los Angeles', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/4ndR-n-gall7_h3f7NYcpQ_96x96.png' }),
  ROCKETS_HOUSTON: new Equipe({ code: 'ROCKETS_HOUSTON', label: 'Rockets de Houston', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/zhO6MIB1UzZmtXLHkJQBmg_96x96.png' }),
  CELTICS: new Equipe({ code: 'CELTICS', label: 'Celtics de Boston', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/GDJBo7eEF8EO5-kDHVpdqw_96x96.png' }),
  RAPTORS: new Equipe({ code: 'RAPTORS', label: 'Raptors de Toronto', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/745IgW4NSvnRxg-W9oczmQ_96x96.png' }),
  MILWAUKEE_BUCKS: new Equipe({ code: 'MILWAUKEE_BUCKS', label: 'Milwaukee Bucks', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Wd6xIEIXpfqg9EZC6PAepQ_96x96.png' }),
  HEAT_MIAMI: new Equipe({ code: 'HEAT_MIAMI', label: 'Heat de Miami', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/0nQXN6OF7wnLY3hJz8lZJQ_96x96.png' }),
  CLIPPERS_LOS_ANGELES: new Equipe({ code: 'CLIPPERS_LOS_ANGELES', label: 'Clippers de Los Angeles', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/F36nQLCQ2FND3za-Eteeqg_96x96.png' }),
  NUGGETS_DE_DENVER: new Equipe({ code: 'NUGGETS_DE_DENVER', label: 'Nuggets de Denver', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/9wPFTOxV_zP1KmRRggJNqQ_96x96.png' }),
  GOLDEN_STATE: new Equipe({ code: 'GOLDEN_STATE', label: 'Warriors de Golden State', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/XD2v321N_-vk7paF53TkAg_96x96.png' }),
  OKLAHOMA_CITY: new Equipe({ code: 'OKLAHOMA_CITY', label: 'Thunder d\'oklahoma City', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/b4bJ9zKFBDykdSIGUrbWdw_96x96.png' }),
  UTAH: new Equipe({ code: 'UTAH', label: 'Jazz de l\'Utah', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/SP_dsmXEKFVZH5N1DQpZ4A_96x96.png' }),
  SPURS_ANTONIO: new Equipe({ code: 'SPURS_ANTONIO', label: 'Spurs de San Antonio', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/FKwMB_85FlZ_7PTt1f7hjQ_96x96.png' }),
  CHICAGO: new Equipe({ code: 'CHICAGO', label: 'Bulls de Chicago', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/ofjScRGiytT__Flak2j4dg_96x96.png' }),
  PORTLAND: new Equipe({ code: 'PORTLAND', label: 'Trail Blazers de Portland', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/_bgagBCd6ieOIt3INWRN_w_96x96.png' }),
  PHEONIX_SUN: new Equipe({ code: 'PHEONIX_SUN', label: 'Pheonix Sun', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/pRr87i24KHWH0UuAc5EamQ_96x96.png' }),
  PHILADELPHIE: new Equipe({ code: 'PHILADELPHIE', label: '76ers de Philadelphie', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/US6KILZue2D5766trEf0Mg_96x96.png' }),
  CLEVELAND: new Equipe({ code: 'CLEVELAND', label: 'Cavaliers de Cleveland', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/NAlGkmv45l1L-3NhwVhDPg_96x96.png' }),
  PELICANS_ORLEANS: new Equipe({ code: 'PELICANS_ORLEANS', label: 'Pelicans de La Nouvelle Orleans', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/JCQO978-AWbg00TQUNPUVg_96x96.png' }),
  DALLAS_MAVERICKS: new Equipe({ code: 'DALLAS_MAVERICKS', label: 'Dallas Mavericks', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/xxxlj9RpmAKJ9P9phstWCQ_96x96.png' }),
  NEW_YORK: new Equipe({ code: 'NEW_YORK', label: 'Knicks de New York', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/-rf7eY39l_0V7J4ekakuKA_96x96.png' }),
  INDIANA: new Equipe({ code: 'INDIANA', label: 'Pacers de l\'Indiana', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/andumiE_wrpDpXvUgqCGYQ_96x96.png' }),
  BROOKLYN: new Equipe({ code: 'BROOKLYN', label: 'Brooklyn', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/iishUmO7vbJBE7iK2CZCdw_96x96.png' }),
  MEMPHIS_GRIZZLIES: new Equipe({ code: 'MEMPHIS_GRIZZLIES', label: 'Memphis Grizzlies', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/3ho45P8yNw-WmQ2m4A4TIA_96x96.png' }),
  KINGS_SACRAMENTO: new Equipe({ code: 'KINGS_SACRAMENTO', label: 'Kings de Sacrento', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/wkCDHakxEThLGoZ4Ven96Q_96x96.png' }),
  ORLANDO: new Equipe({ code: 'ORLANDO', label: 'Magic d\'Orlando', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/p69oiJ4LDsvCJUDQ3wR9PQ_96x96.png' }),
  WIZARDS_DE_WASHINGTON: new Equipe({ code: 'WIZARDS_DE_WASHINGTON', label: 'Wizards de Washington', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/NBkMJapxft4V5kvufec4Jg_96x96.png' }),
  MINNESOTA: new Equipe({ code: 'MINNESOTA', label: 'Timberwolves du Minnesota', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/21Zm6e_zGiWXsaLCQyjVig_96x96.png' }),
  CHARLOTTE: new Equipe({ code: 'CHARLOTTE', label: 'Hornets de Charlotte', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/ToeKy5-TrHAnTCl-qhuuHQ_96x96.png' }),
  PISTONS_DETROIT: new Equipe({ code: 'PISTONS_DETROIT', label: 'Pistons de Détroit', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/qvWE2FgBX0MCqFfciFBDiw_96x96.png' }),
  HAWKS_ATLANTA: new Equipe({ code: 'HAWKS_ATLANTA', label: 'Hawks \'Atlanta', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/pm5l5mtY1elOQAl9ZEcm2A_96x96.png' }),
  HUSKIES_TORONTO: new Equipe({ code: 'HUSKIES_TORONTO', label: 'Huskies de Toronto', codePays : 'FR', url: '' }),
  REDSKINS_SHEBOYGAN: new Equipe({ code: 'REDSKINS_SHEBOYGAN', label: 'Redskins de Sheboygan', codePays : 'FR', url: '' }),
  CAP_CIUDAD_MEX: new Equipe({ code: 'CAP_CIUDAD_MEX', label: 'Capitaines de Ciudad de Mexico', codePays : 'FR', url: '' }),
  OLYM_INDIANA: new Equipe({ code: 'OLYM_INDIANA', label: 'Olympians d\'Indianapolis', codePays : 'FR', url: '' }),
  JETS_INIDIANAPOLIS: new Equipe({ code: 'JETS_INIDIANAPOLIS', label: 'Jets d\'Indianapolis', codePays : 'FR', url: '' }),

};

export const JOUEUR_TENNIS: any = {

  ANNET_KONTAVEIT: new Equipe({ code: 'ANNET_KONTAVEIT', label: 'Anett Kontaveit', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAC7iQ_CiWM1w_96x96.png' }),
  EGOR_GERASIMOV: new Equipe({ code: 'EGOR_GERASIMOV', label: 'Egor Gerasimov', codePays : 'ES', url: URL_PAYER_INCONNU }),
  HERBERT_H: new Equipe({ code: 'HERBERT_H', label: 'Pierre-Hugues Herbert', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACuCQ_A_x-7A_96x96.png' }),
  JANNIK_SINNER: new Equipe({ code: 'JANNIK_SINNER', label: 'Jannik Sinner', codePays : 'FR', url: URL_PAYER_INCONNU }),
  SCHWARTZMAN: new Equipe({ code: 'SCHWARTZMAN', label: 'Diego Schwartzman', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAC91w_RlXQgQ_96x96.png' }),
  STRUFF_JL: new Equipe({ code: 'STRUFF_JL', label: 'Jan-Lennard Struff', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAC1Nw_kibR4w_96x96.png' }),
  NISHIOKA_Y: new Equipe({ code: 'NISHIOKA_Y', label: 'Yoshihito Nishioka', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADnkQ_REcROw_96x96.png' }),
  SIMON_G: new Equipe({ code: 'SIMON_G', label: 'Gilles Simon', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA5kA_FqdpGQ_96x96.png' }),
  D_SHAPOVALOV: new Equipe({ code: 'D_SHAPOVALOV', label: 'Denis Shapovalov', codePays : 'CA', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAHMnA_7J6wJQ_96x96.png' }),
  DANIEL_TARO: new Equipe({ code: 'DANIEL_TARO', label: 'Daniel Taro', codePays : 'JP', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAC9-A_67hYiA_96x96.png' }),
  KUZNETSOV_A: new Equipe({ code: 'KUZNETSOV_A', label: 'Andrey Kuznetsov', codePays : 'RU', url: URL_PAYER_INCONNU }),
  DMITRY_POPKO: new Equipe({ code: 'DMITRY_POPKO', label: 'Dmitry Popko', codePays : 'KZ', url: URL_PAYER_INCONNU }),
  OSCAR_OTTE: new Equipe({ code: 'OSCAR_OTTE', label: 'Oscar Otte', codePays : 'DE', url: URL_PAYER_INCONNU }),
  BROWN_D: new Equipe({ code: 'BROWN_D', label: 'Dustin Brown', codePays : 'DE', url: URL_PAYER_INCONNU }),
  ALX_MULLER: new Equipe({ code: 'ALX_MULLER', label: 'Alexandre Müller', codePays : 'FR', url: URL_PAYER_INCONNU }),
  GARIN_CHRISTIAN: new Equipe({ code: 'GARIN_CHRISTIAN', label: 'Cristian Garin', codePays : 'CL', url: URL_PAYER_INCONNU }),
  YANNICK_HANFMANN: new Equipe({ code: 'YANNICK_HANFMANN', label: 'Yannick Hanfmann', codePays : 'DE', url: URL_PAYER_INCONNU }),
  MEDVEDEV_DANIIL: new Equipe({ code: 'MEDVEDEV_DANIIL', label: 'Daniil Medvedev', codePays : 'RU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAJ-sA_4jc5Zg_96x96.png' }),
  UGO_HUMBERT: new Equipe({ code: 'UGO_HUMBERT', label: 'Ugo Humbert', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AALULA_1aJ1Hw_96x96.png' }),
  ALEX_BUBLIK: new Equipe({ code: 'ALEX_BUBLIK', label: 'Alexander Bublik', codePays : 'KZ', url: URL_PAYER_INCONNU }),
  FELIX_AUGER: new Equipe({ code: 'FELIX_AUGER', label: 'Felix Auger-Aliassime', codePays : 'CA', url: URL_PAYER_INCONNU }),
  MARC_POLMANS: new Equipe({ code: 'MARC_POLMANS', label: 'Marc polmans', codePays : 'AU', url: URL_PAYER_INCONNU }),
  ALESSSANDRO_GIANNESSI: new Equipe({ code: 'ALESSSANDRO_GIANNESSI', label: 'Alessandro Giannessi', codePays : 'IT',
    url: URL_PAYER_INCONNU }),
  RAMOS_VINOLAS: new Equipe({ code: 'RAMOS_VINOLAS', label: 'Albert Ramos-Vinolas', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABBtg_dq6H8A_96x96.png' }),
  NOVAK_DJOKOVIC: new Equipe({ code: 'NOVAK_DJOKOVIC', label: 'Novak Djokovic', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA6Ig_rMyp3w_96x96.png' }),
  STEFANOS_TSITSIPAS: new Equipe({ code: 'STEFANOS_TSITSIPAS', label: 'Stéfanos Tsitsipas', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAHd_g_dw7Yow_96x96.png' }),
  MONFILS: new Equipe({ code: 'MONFILS', label: 'Gael Monfils', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA5_A_h7AvRA_96x96.png' }),
  KAREN_KHACHANOV: new Equipe({ code: 'KAREN_KHACHANOV', label: 'Karen Khachanov', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAFf4A_1fBiMw_96x96.png' }),
  KOHLSCHREIBER: new Equipe({ code: 'KOHLSCHREIBER', label: 'Philipp Kohlschreiber', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA5IA_LESqEA_96x96.png' }),
  DOMINIC_THIEM: new Equipe({ code: 'DOMINIC_THIEM', label: 'Dominic Thiem', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACq5A_q0Bn-g_96x96.png' }),
  MILOS_RAONIC: new Equipe({ code: 'MILOS_RAONIC', label: 'Milos Raonic', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABGvw_dLwnxQ_96x96.png' }),
  FILIP_KRAJINOVIC: new Equipe({ code: 'FILIP_KRAJINOVIC', label: 'Filip Krajinović', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABZug_gJkzfg_96x96.png' }),
  GARCIA_C: new Equipe({ code: 'GARCIA_C', label: 'Caroline Garcia', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAClYw_2oibdg_96x96.png' }),
  ADRIAN_MANNARINO: new Equipe({ code: 'ADRIAN_MANNARINO', label: 'Adrian Mannarino', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA-Fg_V9pkNQ_96x96.png' }),
  JACK_SOCK: new Equipe({ code: 'JACK_SOCK', label: 'Jack Sock', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAChmw_fNNEhA_96x96.png' }),
  MILLMAN_J: new Equipe({ code: 'MILLMAN_J', label: 'John Millman', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACBWw_LtMXRA_96x96.png' }),
  HENRI_KONTINEN: new Equipe({ code: 'HENRI_KONTINEN', label: 'Henri Kontinen ', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABGxA_Z3pxNg_96x96.png' }),
  DODIG_I: new Equipe({ code: 'DODIG_I', label: 'Ivan Dodig ', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA_kw_oSptIA_96x96.png' }),
  FILIP_POLASEK: new Equipe({ code: 'FILIP_POLASEK', label: 'Filip Polášek ', codePays : 'FR', url: URL_PAYER_INCONNU }),
  LAJOVIC_D: new Equipe({ code: 'LAJOVIC_D', label: 'Dusan lajovic ', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACZQg_VI0XpQ_96x96.png' }),
  MATT_REID: new Equipe({ code: 'MATT_REID', label: 'Matt Reid ', codePays : 'FR', url: URL_PAYER_INCONNU }),
  ALEX_DE_MINAUR: new Equipe({ code: 'ALEX_DE_MINAUR', label: 'Alex De Minaur', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AANEpg_hUhIUQ_96x96.png' }),
  NIKOLA_CACIC: new Equipe({ code: 'NIKOLA_CACIC', label: 'Nikola Cacic', codePays : 'FR', url: URL_PAYER_INCONNU }),
  JONNY_OMARA: new Equipe({ code: 'JONNY_OMARA', label: 'Jonny O\'Mara', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADHNA_ay3pPQ_96x96.png' }),
  GIANLUCA_MAGER: new Equipe({ code: 'GIANLUCA_MAGER', label: 'Gianluca Mager', codePays : 'IT', url: URL_PAYER_INCONNU }),
  MARCELO_AREVALO: new Equipe({ code: 'MARCELO_AREVALO', label: 'Marcelo arévalo', codePays : 'FR', url: URL_PAYER_INCONNU }),
  JOHNSON_S: new Equipe({ code: 'JOHNSON_S', label: 'Steve Johnson', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACWXQ_8dHuBQ_96x96.png' }),
  SAM_QUERRY: new Equipe({ code: 'SAM_QUERRY', label: 'Sam Querry', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA7xQ_s2KC0Q_96x96.png' }),
  GRANOLLERS_M: new Equipe({ code: 'GRANOLLERS_M', label: 'Marcel Granollers', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA80A_x2JXTw_96x96.png' }),
  ZEBALLOS_HORACIO: new Equipe({ code: 'ZEBALLOS_HORACIO', label: 'Horacio Zeballos', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA_IA_B2e_ng_96x96.png' }),
  ROBERT_FARAH: new Equipe({ code: 'ROBERT_FARAH', label: 'Robert Farah', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA8qQ_d7ztsg_96x96.png' }),
  JUAN_SEBASTIAN_CABAL: new Equipe({ code: 'JUAN_SEBASTIAN_CABAL', label: 'Juan Sebastián Cabal', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA_xg_vzQHGQ_96x96.png' }),
  CORENTIN_DENOLLY: new Equipe({ code: 'CORENTIN_DENOLLY', label: 'Corentin Denolly', codePays : 'FR', url: URL_PAYER_INCONNU }),
  KYRIAN_JACQUET: new Equipe({ code: 'KYRIAN_JACQUET', label: 'Kyrian Jacquet', codePays : 'FR', url: URL_PAYER_INCONNU }),
  BASILASHVILI_N: new Equipe({ code: 'BASILASHVILI_N', label: 'Nikoloz Basilashvili', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABmXA_owD2iA_96x96.png' }),
  RADU_ALBOT: new Equipe({ code: 'RADU_ALBOT', label: 'Radu Albot', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACuAw_wgsyww_96x96.png' }),
  ATTILA_BALAZS: new Equipe({ code: 'ATTILA_BALAZS', label: 'Attila Balázs', codePays : 'FR', url: URL_PAYER_INCONNU }),
  H_HURKACZ: new Equipe({ code: 'H_HURKACZ', label: 'Hubert Hurkacz', codePays : 'PO', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAJssA_6rhExg_96x96.png' }),
  GRIGO_DIMITROV: new Equipe({ code: 'GRIGO_DIMITROV', label: 'Grigor Dimitrov', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABcHQ_d1xhqA_96x96.png' }),
  KEI_NISHKORI: new Equipe({ code: 'KEI_NISHKORI', label: 'Kei Nishikori', codePays : 'CH', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA9dQ_0SUW4Q_96x96.png' }),
  D_EVANS: new Equipe({ code: 'D_EVANS', label: 'Daniel Evans', codePays : 'FR', url: URL_PAYER_INCONNU }),
  LO_SONEGO: new Equipe({ code: 'LO_SONEGO', label: 'Lorenzo Sonego', codePays : 'FR', url: URL_PAYER_INCONNU }),
  WAWRINKA_S: new Equipe({ code: 'WAWRINKA_S', label: 'Stanislas Wawrinka', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA41A_7mjIKQ_96x96.png' }),
  NORBERT_BOMBOS: new Equipe({ code: 'NORBERT_BOMBOS', label: 'Norbert Gombos', codePays : 'HU', url: URL_PAYER_INCONNU }),
  JURIJ_RODIONOV: new Equipe({ code: 'JURIJ_RODIONOV', label: 'Jurij Rodionov', codePays : 'FR', url: URL_PAYER_INCONNU }),
  A_RUBLEV: new Equipe({ code: 'A_RUBLEV', label: 'Andrey Rublev', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAGhAw_xnNKdw_96x96.png' }),
  CORIC_B: new Equipe({ code: 'CORIC_B', label: 'Borna Coric', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAD8RA_ff2ftw_96x96.png' }),
  FRITZ_T: new Equipe({ code: 'FRITZ_T', label: 'Taylor Fritz', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAITag_zlXxXQ_96x96.png' }),
  DENNIS_NOVAK: new Equipe({ code: 'DENNIS_NOVAK', label: 'Dennis Novak', codePays : 'FR', url: URL_PAYER_INCONNU }),
  KEV_ANDERSON: new Equipe({ code: 'KEV_ANDERSON', label: 'Kevin Anderson', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA8yQ_bm6zfQ_96x96.png' }),
  CARRENO_BUSTA_P: new Equipe({ code: 'CARRENO_BUSTA_P', label: 'Pablo Carreno Busta', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACfYA_jCMJvQ_96x96.png' }),
  SANDGREN_T: new Equipe({ code: 'SANDGREN_T', label: 'Tennys Sandgren', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACPRg_B1TTyw_96x96.png' }),
  JIRI_VESELY: new Equipe({ code: 'JIRI_VESELY', label: 'Jiri Vesely', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACjgQ_kvvp1A_96x96.png' }),
  CAM_NORRIE: new Equipe({ code: 'CAM_NORRIE', label: 'Cameron Norrie', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAF2vw_Ts0Dlw_96x96.png' }),
  THOMPSON_J: new Equipe({ code: 'THOMPSON_J', label: 'Jordan Thompson', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAFWig_K5ULhA_96x96.png' }),
  TOMMY_PAUL: new Equipe({ code: 'TOMMY_PAUL', label: 'Tommy Paul', codePays : 'US', url: URL_PAYER_INCONNU }),
  STEFANO_TRAVAGLIA: new Equipe({ code: 'STEFANO_TRAVAGLIA', label: 'Stefano Travaglia', codePays : 'FR', url: URL_PAYER_INCONNU }),
  VERDASCO_F: new Equipe({ code: 'VERDASCO_F', label: 'Fernando Verdasco', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA4mA_F28rsw_96x96.png' }),
  TIAFOE: new Equipe({ code: 'TIAFOE', label: 'Frances Tiafoe', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAGK7Q_uT2UwQ_96x96.png' }),
  C_MOUTET: new Equipe({ code: 'C_MOUTET', label: 'Corentin Moutet ', codePays : 'FR', url: URL_PAYER_INCONNU }),
  KECMANOVIC_MIOMIR: new Equipe({ code: 'KECMANOVIC_MIOMIR', label: 'Miomir Kecmanović', codePays : 'FR', url: URL_PAYER_INCONNU }),
  MARCO_CECCHINATO: new Equipe({ code: 'MARCO_CECCHINATO', label: 'Marco Cecchinato', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACuBQ_Mr0Hwg_96x96.png' }),
  ALEX_ZVEREV: new Equipe({ code: 'ALEX_ZVEREV', label: 'Alexander Zverev', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADfSw_BjhJlA_96x96.png' }),
  SARA_SORRIBES_TORMO: new Equipe({ code: 'SARA_SORRIBES_TORMO', label: 'Sara Sorribes Tormo', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADr6A_Es7EFg_96x96.png' }),
  GIRON_MARC: new Equipe({ code: 'GIRON_MARC', label: 'Marcos Giron', codePays : 'FR',  url: URL_PAYER_INCONNU }),
  CILIC_MARIN: new Equipe({ code: 'CILIC_MARIN', label: 'Marin Cilic', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA8Gw_7Q-Ekg_96x96.png' }),
  DAVIDOVICH: new Equipe({ code: 'DAVIDOVICH', label: 'Alejandro Davidovich Fokina', codePays : 'ES', url: URL_PAYER_INCONNU }),
  NADAL_RAPH: new Equipe({ code: 'NADAL_RAPH', label: 'Rafael Nadal', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA4lg_JJtvkA_96x96.png' }),
  HUGO_GASTON: new Equipe({ code: 'HUGO_GASTON', label: 'Hugo Gaston', codePays : 'FR', url: URL_PAYER_INCONNU }),
  BEN_BONZI: new Equipe({ code: 'BEN_BONZI', label: 'Benjamin Bonzi', codePays : 'FR', url: URL_PAYER_INCONNU }),
  CORIA_FED: new Equipe({ code: 'CORIA_FED', label: 'Federico Coria', codePays : 'FR', url: URL_PAYER_INCONNU }),
  RUUD_CASPER: new Equipe({ code: 'RUUD_CASPER', label: 'Casper Ruud', codePays : 'FR', url: URL_PAYER_INCONNU }),
  DELBONIS: new Equipe({ code: 'DELBONIS', label: 'Federico Delbonis', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACJXw_Rzc8BQ_96x96.png' }),
  SAL_CARUSO: new Equipe({ code: 'SAL_CARUSO', label: 'Salvatore Caruso', codePays : 'FR', url: URL_PAYER_INCONNU }),
  FUCSOVICS: new Equipe({ code: 'FUCSOVICS', label: 'Martin Fucsovics', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAC6mg_KNo5dQ_96x96.png' }),
  F_LOPEZ: new Equipe({ code: 'F_LOPEZ', label: 'Feliciano Lopez', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA4gQ_oxgjyg_96x96.png' }),
  KLIZAN_MARTIN: new Equipe({ code: 'KLIZAN_MARTIN', label: 'Martin klizan', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA-bw_A4YdQQ_96x96.png' }),
  KATERINA_SINIAKOVA: new Equipe({ code: 'KATERINA_SINIAKOVA', label: 'Katerina Siniakova', codePays : 'CZ', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEauA_abBoPA_96x96.png' }),
  EKA_ALEXANDROVA: new Equipe({ code: 'EKA_ALEXANDROVA', label: 'Ekaterina Alexandrova', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEIrw_Vq1ysg_96x96.png' }),
  YASTREMSKA: new Equipe({ code: 'YASTREMSKA', label: 'Dayana Yastremska', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AALubA_7_GdkA_96x96.png' }),
  GRETT_MINNEN: new Equipe({ code: 'GRETT_MINNEN', label: 'Greet Minnen', codePays : 'AL', url: URL_PAYER_INCONNU }),
  SASNOVICH_ALIA: new Equipe({ code: 'SASNOVICH_ALIA', label: 'Aliaksandra Sasnovich', codePays : 'BY', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACzTg_-AyjFA_96x96.png' }),
  PERA_BERNARDA: new Equipe({ code: 'PERA_BERNARDA', label: 'Bernada Pera', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEIrQ__XMhzQ_96x96.png' }),
  ZIDANSEK_TAMA: new Equipe({ code: 'ZIDANSEK_TAMA', label: 'Tamara Zidansek', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAGu2w_F_xPXw_96x96.png' }),
  MAGDA_LINETTE: new Equipe({ code: 'MAGDA_LINETTE', label: 'Magda Linette', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAClMQ_og6ijA_96x96.png' }),
  STEPHANIE_VOGELE: new Equipe({ code: 'STEPHANIE_VOGELE', label: 'Stephanie Vogele', codePays : 'FR', url: URL_PAYER_INCONNU }),
  KATHRINA_GERLACH: new Equipe({ code: 'KATHRINA_GERLACH', label: 'Kathrina Gerlach', codePays : 'FR', url: URL_PAYER_INCONNU }),
  MAYO_HIBI: new Equipe({ code: 'MAYO_HIBI', label: 'Mayo Hibi', codePays : 'FR', url: URL_PAYER_INCONNU }),
  YOU_XIAODI: new Equipe({ code: 'YOU_XIAODI', label: 'You Xiaodi', codePays : 'FR', url: URL_PAYER_INCONNU }),
  S_MENDEZ: new Equipe({ code: 'S_MENDEZ', label: 'Seone Mendez', codePays : 'FR', url: URL_PAYER_INCONNU }),
  MARIE_BENOIT: new Equipe({ code: 'MARIE_BENOIT', label: 'Marie Benoit', codePays : 'FR', url: URL_PAYER_INCONNU }),
  WANG_XINYU: new Equipe({ code: 'WANG_XINYU', label: 'Wang Xinyu', codePays : 'FR', url: URL_PAYER_INCONNU }),
  IRINA_MARIA_BARA: new Equipe({ code: 'IRINA_MARIA_BARA', label: 'Irina Maria Bara', codePays : 'RO', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADL1w_BUUS2Q_96x96.png' }),
  GABRIELA_TALABA: new Equipe({ code: 'GABRIELA_TALABA', label: 'Gabriela Talaba', codePays : 'RO', url: URL_PAYER_INCONNU }),
  YUKI_NAITO: new Equipe({ code: 'YUKI_NAITO', label: 'Yuki Naito', codePays : 'CH', url: URL_PAYER_INCONNU }),
  CHLOE_PAQUET: new Equipe({ code: 'CHLOE_PAQUET', label: 'Cloé Paquet', codePays : 'FR', url: URL_PAYER_INCONNU }),
  ROBIN_ANDERSON: new Equipe({ code: 'ROBIN_ANDERSON', label: 'Robin Anderson', codePays : 'US', url: URL_PAYER_INCONNU }),
  DANIELLE_LAO: new Equipe({ code: 'DANIELLE_LAO', label: 'Danielle Lao', codePays : 'US', url: URL_PAYER_INCONNU }),
  CHARDY_J: new Equipe({ code: 'CHARDY_J', label: 'Jérémy Chardy', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA91Q_QzvS8g_96x96.png' }),
  GASQUET_R: new Equipe({ code: 'GASQUET_R', label: 'Richard Gasquet', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA4Tg_trA-Uw_96x96.png' }),
  MACKENZIE: new Equipe({ code: 'MACKENZIE', label: 'Mackenzie McDonald', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAD3zg_sYzO4Q_96x96.png' }),
  JASON_KUBLER: new Equipe({ code: 'JASON_KUBLER', label: 'Jason Kubler', codePays : 'AU', url: URL_PAYER_INCONNU }),
  BOUCHIER_H: new Equipe({ code: 'BOUCHIER_H', label: 'Harry Bourchier', codePays : 'AU', url: URL_PAYER_INCONNU }),
  M_YMER: new Equipe({ code: 'M_YMER', label: 'Mikael Ymer', codePays : 'SU', url: URL_PAYER_INCONNU }),
  PEDRO_SOUSA: new Equipe({ code: 'PEDRO_SOUSA', label: 'Pedro Sousa', codePays : 'PT', url: URL_PAYER_INCONNU }),
  LI_TU: new Equipe({ code: 'LI_TU', label: 'Li TU', codePays : 'AU', url: URL_PAYER_INCONNU }),
  BLAKE_MOTT: new Equipe({ code: 'BLAKE_MOTT', label: 'Blake Mott', codePays : 'AU', url: URL_PAYER_INCONNU }),
  KOKKINAKIS: new Equipe({ code: 'KOKKINAKIS', label: 'Thanasi Kokkinakis', codePays : 'AU', url: URL_PAYER_INCONNU }),
  ALEX_BOLT: new Equipe({ code: 'ALEX_BOLT', label: 'Alex Bolt', codePays : 'AU', url: URL_PAYER_INCONNU }),
  SUMIT_NAGAL: new Equipe({ code: 'SUMIT_NAGAL', label: 'Sumit Nagal', codePays : 'IN', url: URL_PAYER_INCONNU }),
  BERANKIS_R: new Equipe({ code: 'BERANKIS_R', label: 'Ricardas Berankis', codePays : 'LT', url: URL_PAYER_INCONNU }),
  LLOYD_HARRIS: new Equipe({ code: 'LLOYD_HARRIS', label: 'Lloyd Harris', codePays : 'ZA', url: URL_PAYER_INCONNU }),
  DOI_M: new Equipe({ code: 'DOI_M', label: 'Misaki Doi', codePays : 'JP', url: URL_PAYER_INCONNU }),
  PAVLYUCHENKOVA: new Equipe({ code: 'PAVLYUCHENKOVA', label: 'Anastasia Pavlyuchenkova', codePays : 'RU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABMWg_OQ7vOA_96x96.png' }),
  CLARA_BUREL: new Equipe({ code: 'CLARA_BUREL', label: 'Clara Burel', codePays : 'FR', url: URL_PAYER_INCONNU }),
  CAMILA_GIORGI: new Equipe({ code: 'CAMILA_GIORGI', label: 'Camilia Giorgi', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACtFQ_ZphOBg_96x96.png' }),
  HSIEH_SU_WEI: new Equipe({ code: 'HSIEH_SU_WEI', label: 'Hsieh Su-wei', codePays : 'TW', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABJ-A_voipsA_96x96.png' }),
  ALISON_VAN_UYTVANCK: new Equipe({ code: 'ALISON_VAN_UYTVANCK', label: 'Alison Van Uytvanck', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADF_w_8sPS1g_96x96.png' }),
  GAVRILOVA_D: new Equipe({ code: 'GAVRILOVA_D', label: 'Daria Gavrilova', codePays : 'AU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACgIg_PTrhkg_96x96.png' }),
  WILLIAMS_S: new Equipe({ code: 'WILLIAMS_S', label: 'Serana Williams', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABHTg_HpxVdg_96x96.png' }),
  VONDROUSOVA_M: new Equipe({ code: 'VONDROUSOVA_M', label: 'Markéta Vondroušová', codePays : 'CZ', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAJU5A_2WeRLw_96x96.png' }),
  GRACHEVA_V: new Equipe({ code: 'GRACHEVA_V', label: 'Varvara Gracheva', codePays : 'RU', url: URL_PAYER_INCONNU }),
  PLISKOVA_K: new Equipe({ code: 'PLISKOVA_K', label: 'Karolína Plíšková', codePays : 'CZ', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABQ_A_kNvnSA_96x96.png' }),
  VEKIC_D: new Equipe({ code: 'VEKIC_D', label: 'Donna Vekic', codePays : 'HR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADF0Q_zp1DJg_96x96.png' }),
  PIRONKOVA: new Equipe({ code: 'PIRONKOVA', label: 'Tsvetana Pironkova', codePays : 'BG', url: URL_PAYER_INCONNU }),
  KYRGIOS_NICK: new Equipe({ code: 'KYRGIOS_NICK', label: 'Nick Kyrgios', codePays : 'AU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAD0Gg_sIFndg_96x96.png' }),
  MMOH_MICH: new Equipe({ code: 'MMOH_MICH', label: 'Michael Mmoh', codePays : 'AU', url: URL_PAYER_INCONNU }),
  DUCKWORTH_J: new Equipe({ code: 'DUCKWORTH_J', label: 'James Duckworth', codePays : 'AU', url: URL_PAYER_INCONNU }),
  MACHAC_T: new Equipe({ code: 'MACHAC_T', label: 'Tomas Machac', codePays : 'CZ', url: URL_PAYER_INCONNU }),
  QUENTIN_HALYS: new Equipe({ code: 'QUENTIN_HALYS', label: 'Quentin Halys', codePays : 'FR', url: URL_PAYER_INCONNU }),
  SUGITA_Y: new Equipe({ code: 'SUGITA_Y', label: 'Sugita Yuichi', codePays : 'JP', url: URL_PAYER_INCONNU }),
  SILVA_FERREIRA: new Equipe({ code: 'SILVA_FERREIRA', label: 'Frederico Ferreira Silva', codePays : 'PT', url: URL_PAYER_INCONNU }),
  BORNA_GOJO: new Equipe({ code: 'BORNA_GOJO', label: 'Borna Gojo', codePays : 'HR', url: URL_PAYER_INCONNU }),
  STEBE_CE_MAR: new Equipe({ code: 'STEBE_CE_MAR', label: 'Cedrik-MarcelStebe', codePays : 'AL', url: URL_PAYER_INCONNU }),
  POPYRIN: new Equipe({ code: 'POPYRIN', label: 'Alexei Popyrin', codePays : 'AU', url: URL_PAYER_INCONNU }),
  ANDREW_HARRIS: new Equipe({ code: 'ANDREW_HARRIS', label: 'Andrew Harris', codePays : 'AU', url: URL_PAYER_INCONNU }),
  M_CRESSY: new Equipe({ code: 'M_CRESSY', label: 'Maxime Cressy', codePays : 'US', url: URL_PAYER_INCONNU }),
  TROICKI_V: new Equipe({ code: 'TROICKI_V', label: 'Viktor Troicki', codePays : 'RS', url: URL_PAYER_INCONNU }),
  RUUSUVUORI: new Equipe({ code: 'RUUSUVUORI', label: 'Emil Ruusuvuori', codePays : 'FI', url: URL_PAYER_INCONNU }),
  PODOROSKA: new Equipe({ code: 'PODOROSKA', label: 'Nadia Podoroska', codePays : 'AR', url: URL_PAYER_INCONNU }),
  PETRA_KVITOVA: new Equipe({ code: 'PETRA_KVITOVA', label: 'Petra Kvitová', codePays : 'CZ', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABNfA_yqn3zg_96x96.png' }),
  PURCELL: new Equipe({ code: 'PURCELL', label: 'Max Purcell', codePays : 'AU', url: URL_PAYER_INCONNU }),
  B_PAIRE: new Equipe({ code: 'B_PAIRE', label: 'Benoît Paire', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABWyg_Txro0A_96x96.png' }),
  STAKOVSKY: new Equipe({ code: 'STAKOVSKY', label: 'Serhiy Stakhovsky', codePays : 'UA', url: URL_PAYER_INCONNU }),
  FIONA_FERRO: new Equipe({ code: 'FIONA_FERRO', label: 'Fiona Ferro', codePays : 'FR', url: URL_PAYER_INCONNU }),
  KOPFER_DO: new Equipe({ code: 'KOPFER_DO', label: 'Dominik Köpfer', codePays : 'AL', url: URL_PAYER_INCONNU }),
  DELLIEN_HUGO: new Equipe({ code: 'DELLIEN_HUGO', label: 'Hugo Dellien', codePays : 'BO', url: URL_PAYER_INCONNU }),
  LONDERO_JUAN: new Equipe({ code: 'LONDERO_JUAN', label: 'Juan Ignacio Londero', codePays : 'AR', url: URL_PAYER_INCONNU }),
  COPPEJANS: new Equipe({ code: 'COPPEJANS', label: 'Kimmer Coppejans', codePays : 'AL', url: URL_PAYER_INCONNU }),
  YASUTAKA_UCHI: new Equipe({ code: 'YASUTAKA_UCHI', label: 'Yasutaka Uchiyama', codePays : 'CH', url: URL_PAYER_INCONNU }),
  KUKUSHKIN: new Equipe({ code: 'KUKUSHKIN', label: 'Mikhail Kukushkin', codePays : 'KZ', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABBKw_nTzcsQ_96x96.png' }),
  KARATSEV: new Equipe({ code: 'KARATSEV', label: 'Aslan Karatsev', codePays : 'RU', url: URL_PAYER_INCONNU }),
  MARTINEZ_PEDRO: new Equipe({ code: 'MARTINEZ_PEDRO', label: 'Pedro Martínez', codePays : 'ES', url: URL_PAYER_INCONNU }),
  DAMIR_DHUMHUR: new Equipe({ code: 'DAMIR_DHUMHUR', label: 'Damir Džumhur', codePays : 'BA', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADAFA_D0aIUQ_96x96.png' }),
  BENDENE_ALJAZ: new Equipe({ code: 'BENDENE_ALJAZ', label: 'Aljaž Bedene', codePays : 'SI', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACUhg_eDJ8Ng_96x96.png' }),
  SABALENKA: new Equipe({ code: 'SABALENKA', label: 'Aryna Sabalenka', codePays : 'BY', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAJoOg_cNCKvw_96x96.png' }),
  KUZMOVA_VIK: new Equipe({ code: 'KUZMOVA_VIK', label: 'Viktória Kužmová', codePays : 'SK', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAH5_g_zOb-mA_96x96.png' }),
  ZVONAREVA: new Equipe({ code: 'ZVONAREVA', label: 'Vera Zvonareva', codePays : 'RU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABHeg_gTMQZw_96x96.png' }),
  ELEN_RYBAKINA: new Equipe({ code: 'ELEN_RYBAKINA', label: 'Elena Rybakina', codePays : 'KZ', url: URL_PAYER_INCONNU }),
  MARIA_TIG: new Equipe({ code: 'MARIA_TIG', label: 'Patricia Maria Țig', codePays : 'RO', url: URL_PAYER_INCONNU }),
  CIRSTEA: new Equipe({ code: 'CIRSTEA', label: 'Sorana Cîrstea', codePays : 'RO', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABNEA_xm5lFw_96x96.png' }),
  LIZETTE_CABRERA: new Equipe({ code: 'LIZETTE_CABRERA', label: 'Lizette Cabrera', codePays : 'AU', url: URL_PAYER_INCONNU }),
  HALEP_S: new Equipe({ code: 'HALEP_S', label: 'Simona Halep', codePays : 'RO', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACL_Q_U-3ZmQ_96x96.png' }),
  CORNET_A: new Equipe({ code: 'CORNET_A', label: 'Alizé Cornet', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABJeA_2RTL5g_96x96.png' }),
  SAVINYKH: new Equipe({ code: 'SAVINYKH', label: 'Valeria Savinykh', codePays : 'RU', url: URL_PAYER_INCONNU }),
  RISKE_A: new Equipe({ code: 'RISKE_A', label: 'Alison Riske', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABN3g_J10oow_96x96.png' }),
  POTAPOVA_A: new Equipe({ code: 'POTAPOVA_A', label: 'Anastasia Potapova', codePays : 'RU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAOSpg_YuQ9pQ_96x96.png' }),
  BLINKOVA: new Equipe({ code: 'SAVINYKH', label: 'Anna Blinkova', codePays : 'RU', url: URL_PAYER_INCONNU }),
  BIANCA_ANDREESCU: new Equipe({ code: 'BIANCA_ANDREESCU', label: 'Bianca Andreescu', codePays : 'CA', url: URL_PAYER_INCONNU }),
  BUZARNESCU: new Equipe({ code: 'BUZARNESCU', label: 'Mihaela Buzărnescu', codePays : 'RO', url: URL_PAYER_INCONNU }),
  KUDERMETOVA: new Equipe({ code: 'KUDERMETOVA', label: 'Veronika Kudermetova', codePays : 'RO', url: URL_PAYER_INCONNU }),
  KOSTYUK: new Equipe({ code: 'KOSTYUK', label: 'Marta Kostyuk', codePays : 'RO', url: URL_PAYER_INCONNU }),
  JOHA_KONTA: new Equipe({ code: 'JOHA_KONTA', label: 'Johanna Konta', codePays : 'GB', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACyzA_XM34vA_96x96.png' }),
  KAJA_JUAN: new Equipe({ code: 'KAJA_JUAN', label: 'Kaja Juvan', codePays : 'SI', url: URL_PAYER_INCONNU }),
  BARDY_ASH: new Equipe({ code: 'BARDY_ASH', label: 'Ashleigh Barty', codePays : 'AU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADAyA_gTr24w_96x96.png' }),
  DANKA_KOVINIC: new Equipe({ code: 'DANKA_KOVINIC', label: 'Danka Kovinić', codePays : 'ME', url: URL_PAYER_INCONNU }),
  MARTIC_PETRA: new Equipe({ code: 'MARTIC_PETRA', label: 'Petra Martić', codePays : 'HR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABM-A_CzVWzg_96x96.png' }),
  DANILVIC_OLGA: new Equipe({ code: 'DANILVIC_OLGA', label: 'Olga Danilović', codePays : 'RS', url: URL_PAYER_INCONNU }),
  ROGERS_SHELBY: new Equipe({ code: 'ROGERS_SHELBY', label: 'Shelby Rogers', codePays : 'US', url: URL_PAYER_INCONNU }),
  JONES_FRANCESCA: new Equipe({ code: 'JONES_FRANCESCA', label: 'Francesca Jones', codePays : 'GB', url: URL_PAYER_INCONNU }),
  STOSUR_SAMANTHA: new Equipe({ code: 'STOSUR_SAMANTHA', label: 'Samantha Stosur', codePays : 'AU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABH_Q_e0K5xA_96x96.png' }),
  AIAVA_DESTANEE: new Equipe({ code: 'AIAVA_DESTANEE', label: 'Destanee Aiava', codePays : 'AU', url: URL_PAYER_INCONNU }),
  SLOANE_STEPHENS: new Equipe({ code: 'SLOANE_STEPHENS', label: 'Sloane Stephens', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABadg_hMHBJQ_96x96.png' }),
  PUTINTSEVA: new Equipe({ code: 'PUTINTSEVA', label: 'Yulia Putintseva', codePays : 'KZ', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACx6Q_dgBQmw_96x96.png' }),
  COLLINS_DANIELLE: new Equipe({ code: 'COLLINS_DANIELLE', label: 'Danielle Collins', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADkkw_ULB7MA_96x96.png' }),
  BOGDAN_ANA: new Equipe({ code: 'BOGDAN_ANA', label: 'Ana Bogdan', codePays : 'RO', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAChiw_7szkyg_96x96.png' }),
  MONA_BARTHEL: new Equipe({ code: 'MONA_BARTHEL', label: 'Mona Barthel', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACnVw_AVL9FA_96x96.png' }),
  COCCIARETTO: new Equipe({ code: 'COCCIARETTO', label: 'Elisabetta Cocciaretto', codePays : 'IT', url: URL_PAYER_INCONNU }),
  PAOLINI: new Equipe({ code: 'PAOLINI', label: 'Jasmine Paolini', codePays : 'IT', url: URL_PAYER_INCONNU }),
  SHERIF_MAYAR: new Equipe({ code: 'SHERIF_MAYAR', label: 'Mayar Sherif', codePays : 'EG', url: URL_PAYER_INCONNU }),
  WANG_YAFAN: new Equipe({ code: 'WANG_YAFAN', label: 'Wang Yafan', codePays : 'CN', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADLOQ_kH_ABQ_96x96.png' }),
  CORI_GAUFF: new Equipe({ code: 'CORI_GAUFF', label: 'Cori Gauff', codePays : 'US', url: URL_PAYER_INCONNU }),
  ANISIMOVA_AMANDA: new Equipe({ code: 'CORI_GAUFF', label: 'Amanda Anisimova', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AARKZQ_-4mq1A_96x96.png' }),
  TEICHMANN: new Equipe({ code: 'TEICHMANN', label: 'Jil Teichmann', codePays : 'CH', url: URL_PAYER_INCONNU }),
  TREVISAN_MART: new Equipe({ code: 'TREVISAN_MART', label: 'Martina Trevisan', codePays : 'IT', url: URL_PAYER_INCONNU }),
  EKATERINA_ALEXAN: new Equipe({ code: 'EKATERINA_ALEXAN', label: 'Ekaterina Alexandrova', codePays : 'CS', url: URL_PAYER_INCONNU }),
  BRADY_JENN: new Equipe({ code: 'BRADY_JENN', label: 'Jennifer Brady', codePays : 'US', url: URL_PAYER_INCONNU }),
  ALIONA_BOLSOVA: new Equipe({ code: 'ALIONA_BOLSOVA', label: 'Aliona Bolsova', codePays : 'ES', url: URL_PAYER_INCONNU }),
  MLADENOVIC: new Equipe({ code: 'MLADENOVIC', label: 'Kristina Mladenovic', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACDOQ_hhRmag_96x96.png' }),
  SAKKARI: new Equipe({ code: 'OPELKA', label: 'María Sakkari', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEBng_-D5V5w_96x96.png' }),
  MADISON_BRENGLE: new Equipe({ code: 'MADISON_BRENGLE', label: 'Madison Brengle', codePays : 'US', url: URL_PAYER_INCONNU }),
  ARINA_RODIONOVA: new Equipe({ code: 'ARINA_RODIONOVA', label: 'Arina Rodionova', codePays : 'AU', url: URL_PAYER_INCONNU }),
  KRYSTYNA_PLISKOVA: new Equipe({ code: 'KRYSTYNA_PLISKOVA', label: 'Kristýna Plíšková', codePays : 'CZ', url: URL_PAYER_INCONNU }),
  HEATHER_WATSON: new Equipe({ code: 'HEATHER_WATSON', label: 'Heather Watson', codePays : 'GB', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAChvA_iT5MkA_96x96.png' }),
  BORBORA_STRYCOVA: new Equipe({ code: 'BORBORA_STRYCOVA', label: 'Barbora Strýcová', codePays : 'CZ', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABH_g_foncpw_96x96.png' }),
  KUZNETOVA_SVE: new Equipe({ code: 'KUZNETOVA_SVE', label: 'Svetlana Kuznetsova', codePays : 'RU', url: URL_PAYER_INCONNU }),
  MARIE_BOUZKOVA: new Equipe({ code: 'MARIE_BOUZKOVA', label: 'Marie Bouzková', codePays : 'CZ', url: URL_PAYER_INCONNU }),
  ELINA_SVITOLINA: new Equipe({ code: 'ELINA_SVITOLINA', label: 'Elina Svitolina', codePays : 'UK', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADIXQ_rLD68A_96x96.png' }),
  ZHU_LIN: new Equipe({ code: 'ZHU_LIN', label: 'Zhu Lin', codePays : 'CH', url: URL_PAYER_INCONNU }),
  WITHNEY_OSUIGWE: new Equipe({ code: 'WITHNEY_OSUIGWE', label: 'Whitney Osuigwe', codePays : 'US', url: URL_PAYER_INCONNU }),
  AZARENKA_VICTORIA: new Equipe({ code: 'AZARENKA_VICTORIA', label: 'Victoria Azarenka', codePays : 'BY', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABKSQ_fEI1sw_96x96.png' }),
  PEGULA_JESS: new Equipe({ code: 'PEGULA_JESS', label: 'Jessica Pegula', codePays : 'US', url: URL_PAYER_INCONNU }),
  ANAS_SEVASTOVA: new Equipe({ code: 'ANAS_SEVASTOVA', label: 'Anastasija Sevastova', codePays : 'LV', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABNTA_-hTLPA_96x96.png' }),
  KANEPI: new Equipe({ code: 'KANEPI', label: 'Kaia Kanepi', codePays : 'EE', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABKIQ_-mW4Og_96x96.png' }),
  BENCIC_B: new Equipe({ code: 'BENCIC_B', label: 'Belinda Bencic', codePays : 'SU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAD51Q_ZhaXIQ_96x96.png' }),
  LAREN_DAVIS: new Equipe({ code: 'LAREN_DAVIS', label: 'Lauren Davis', codePays : 'US', url: URL_PAYER_INCONNU }),
  SOFIA_KENIN: new Equipe({ code: 'SOFIA_KENIN', label: 'Sofia Kenin', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAFnOA_5Ofu4g_96x96.png' }),
  MADDISON_INGLIS: new Equipe({ code: 'MADDISON_INGLIS', label: 'Maddison Inglis', codePays : 'AU', url: URL_PAYER_INCONNU }),
  NAO_HIBINO: new Equipe({ code: 'NAO_HIBINO', label: 'Nao Hibino', codePays : 'JP', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEbAg_38MFuw_96x96.png' }),
  ASTRA_SHARMA: new Equipe({ code: 'ASTRA_SHARMA', label: 'Astra Sharma', codePays : 'AU', url: URL_PAYER_INCONNU }),
  MUGURUZA_GARBINE: new Equipe({ code: 'MUGURUZA_GARBINE', label: 'Garbiñe Muguruza', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADGWA_Ri4Gjw_96x96.png' }),
  GASPARYAN: new Equipe({ code: 'GASPARYAN', label: 'Margarita Gasparyan', codePays : 'RU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACg6Q_1xN2eg_96x96.png' }),
  ANN_LI: new Equipe({ code: 'ANN_LI', label: 'Ann Li', codePays : 'US', url: URL_PAYER_INCONNU }),
  ZHANG_SHUAI: new Equipe({ code: 'ZHANG_SHUAI', label: 'Zhang Shuai', codePays : 'CH', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABMlw_bRs8zA_96x96.png' }),
  ANNIE_FERNANDEZ: new Equipe({ code: 'ANNIE_FERNANDEZ', label: 'Leylah Annie Fernandez', codePays : 'CA', url: URL_PAYER_INCONNU }),
  ELISE_MERTENS: new Equipe({ code: 'ELISE_MERTENS', label: 'Elise Mertens', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEy1w_J93OYw_96x96.png' }),
  SAMSONOVA: new Equipe({ code: 'SAMSONOVA', label: 'Liudmila Samsonova', codePays : 'RU', url: URL_PAYER_INCONNU }),
  PAULA_GIBERT: new Equipe({ code: 'PAULA_GIBERT', label: 'Paula Badosa Gibert', codePays : 'ES', url: URL_PAYER_INCONNU }),
  NADIA_PODOROSKA: new Equipe({ code: 'NADIA_PODOROSKA', label: 'Nadia Podoroska', codePays : 'CH', url: URL_PAYER_INCONNU }),
  MCHALE_CHRIS: new Equipe({ code: 'MCHALE_CHRIS', label: 'Christina McHale', codePays : 'US', url: URL_PAYER_INCONNU }),
  FERNANDEZ_L: new Equipe({ code: 'FERNANDEZ_L', label: 'Leylah Fernandez', codePays : 'RU', url: URL_PAYER_INCONNU }),
  BERETTINI: new Equipe({ code: 'BERETTINI', label: 'Matteo Berrettini', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAG4jw_-y2_NQ_96x96.png' }),
  FOGINI: new Equipe({ code: 'FOGINI', label: 'Fabio Fognini', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA8Sg_vSOR8Q_96x96.png' }),
  GOFFIN: new Equipe({ code: 'GOFFIN', label: 'David Goffin', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABk7g_ADSy4A_96x96.png' }),
  CHRIS_O_CONNELL: new Equipe({ code: 'CHRIS_O_CONNELL', label: 'Christopher O Connell', codePays : 'AU', url: URL_PAYER_INCONNU }),
  WANG_QIANG: new Equipe({ code: 'WANG_QIANG', label: 'Wang Qiang', codePays : 'CH', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACzFg_eoBJ_A_96x96.png' }),
  GADECKI_OLIVIA: new Equipe({ code: 'WANG_QIANG', label: 'Olivia Gadecki', codePays : 'AU', url: URL_PAYER_INCONNU }),
  STORM_SANDERS: new Equipe({ code: 'WANG_QIANG', label: 'Storm Sanders', codePays : 'AU', url: URL_PAYER_INCONNU }),
  MCNALLY: new Equipe({ code: 'MCNALLY', label: 'Catherine McNally', codePays : 'US', url: URL_PAYER_INCONNU }),
  OSAKA: new Equipe({ code: 'OSAKA', label: 'Naomi Osaka', codePays : 'CH', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEDrA_5AihrQ_96x96.png' }),
  ONS_JABEUR: new Equipe({ code: 'ONS_JABEUR', label: 'Ons Jabeur', codePays : 'TU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADYaQ_uXxq7g_96x96.png' }),
  SIEGEMUND: new Equipe({ code: 'SIEGEMUND', label: 'Laura Siegemund', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACShA_eEH6Fg_96x96.png' }),
  POUILLE: new Equipe({ code: 'POUILLE', label: 'Lucas Pouille', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AADhZw_d3j7Kw_96x96.png' }),
  TOMLJANOVIC: new Equipe({ code: 'TOMLJANOVIC', label: 'Ajla Tomljanović', codePays : 'AU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACGtg_JhEdaA_96x96.png' }),
  JOHN_SMITH: new Equipe({ code: 'JOHN_SMITH', label: 'John-Patrick Smith', codePays : 'AU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABCjg_yQ0I1w_96x96.png' }),
  KOEPFER: new Equipe({ code: 'KOEPFER', label: 'Dominik Kopfer', codePays : 'AL', url: URL_PAYER_INCONNU }),
  TIRANTE: new Equipe({ code: 'TIRANTE', label: 'Thiago Agustin Tirante', codePays : 'AR', url: URL_PAYER_INCONNU }),
  KERBER: new Equipe({ code: 'KERBER', label: 'Angelique Kerber', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABMeg_mX_ZrA_96x96.png' }),
  BUYUKAKCAY: new Equipe({ code: 'BUYUKAKCAY', label: 'Çağla Buyukakcay', codePays : 'CH', url: URL_PAYER_INCONNU }),
  DODIN: new Equipe({ code: 'DODIN', label: 'Océane Dodin', codePays : 'DE', url: URL_PAYER_INCONNU }),
  MARTINCOVA: new Equipe({ code: 'MARTINCOVA', label: 'Tereza Martincová', codePays : 'DE', url: URL_PAYER_INCONNU }),
  KASATKINA_DARIA: new Equipe({ code: 'KASATKINA_DARIA', label: 'Daria Kasatkina', codePays : 'RU', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAIFEg_cU8bFg_96x96.png' }),
  BOUCHARD_EUGENIE: new Equipe({ code: 'BOUCHARD_EUGENIE', label: 'Eugenie Bouchard', codePays : 'CA', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACsGw_UXxkcg_96x96.png' }),
  CARO_DOLEHIDE: new Equipe({ code: 'CARO_DOLEHIDE', label: 'Caroline Dolehide', codePays : 'US', url: URL_PAYER_INCONNU }),
  ROGER_FEDERER: new Equipe({ code: 'ROGER_FEDERER', label: 'Roger Federer', codePays : 'CA', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA4Bg_hPdDsQ_96x96.png' }),
  CONS_LESTIENNE: new Equipe({ code: 'CONS_LESTIENNE', label: 'Constant Lestienne', codePays : 'FR', url: URL_PAYER_INCONNU }),
  VASEK_POSPISIL: new Equipe({ code: 'VASEK_POSPISIL', label: 'Vasek Pospisil', codePays : 'CA', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABBiw_GP050w_96x96.png' }),
  BAUTISTA_AGUT: new Equipe({ code: 'BAUTISTA_AGUT', label: 'Roberto Bautista-Agut', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABBUA__ZJd7Q_96x96.png' }),
  LASLO_DJERE: new Equipe({ code: 'LASLO_DJERE', label: 'Laslo Djere', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAF7zw_IaHmlQ_96x96.png' }),
  MUSETTI: new Equipe({ code: 'MUSETTI', label: 'Lorenzo Musetti', codePays : 'FR', url: URL_PAYER_INCONNU }),
  ZEPPIERI: new Equipe({ code: 'ZEPPIERI', label: 'Giulio Zeppieri', codePays : 'IT', url: URL_PAYER_INCONNU }),
  KWON: new Equipe({ code: 'KWON', label: 'Soonwoo Kwon', codePays : '', url: URL_PAYER_INCONNU }),
  RUNE: new Equipe({ code: 'RUNE', label: 'Holger Vitus Nødskov Rune', codePays : 'SU', url: URL_PAYER_INCONNU }),
  KOVALIK: new Equipe({ code: 'KOVALIK', label: 'Jozef Kovalik', codePays : '', url: URL_PAYER_INCONNU }),
  BAGNIS: new Equipe({ code: 'BAGNIS', label: 'Facundo Bagnis', codePays : 'AR', url: URL_PAYER_INCONNU }),

  FLIPKENS_KIRS: new Equipe({ code: 'FLIPKENS_KIRS', label: 'Kirsten Flipkens', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABIGQ_U1vPqA_96x96.png' }),
  GOVORTSOVA_OLGA: new Equipe({ code: 'GOVORTSOVA_OLGA', label: 'Olga Govortsova', codePays : 'US', url: URL_PAYER_INCONNU }),
  MONGOMERY_ROBIN: new Equipe({ code: 'MONGOMERY_ROBIN', label: 'Robin Montgomery', codePays : 'US', url: URL_PAYER_INCONNU }),
  SCHMIEDLOVA_ANNA: new Equipe({ code: 'SCHMIEDLOVA_ANNA', label: 'Anna Karolína Schmiedlová', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAC04A_pbA7wg_96x96.png' }),
  KUCOVA_KRI: new Equipe({ code: 'KUCOVA_KRI', label: 'Kristína Kučová', codePays : 'US', url: URL_PAYER_INCONNU }),
  RENATA_ZARA: new Equipe({ code: 'RENATA_ZARA', label: 'Renata Zarazúa', codePays : 'US', url: URL_PAYER_INCONNU }),
  AHN_KRISTIE: new Equipe({ code: 'AHN_KRISTIE', label: 'Kristie Ahn', codePays : 'US', url: URL_PAYER_INCONNU }),
  REBECCA_PERTERSON: new Equipe({ code: 'REBECCA_PERTERSON', label: 'Rebecca Peterson', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAEmEQ_IhCSfQ_96x96.png' }),
  KATRINA_SCOTT: new Equipe({ code: 'KATRINA_SCOTT', label: 'Katrina Scott', codePays : 'US', url: URL_PAYER_INCONNU }),
  SWIATEK: new Equipe({ code: 'SWIATEK', label: 'Iga Swiątek', codePays : 'US', url: URL_PAYER_INCONNU }),
  PETKOVIC: new Equipe({ code: 'PETKOVIC', label: 'Andrea Petkovic', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AABMew_m2tmnA_96x96.png' }),
  DIYAS: new Equipe({ code: 'DIYAS', label: 'Zarina Diyas', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AACOWw_PYORpw_96x96.png' }),
  ISNER: new Equipe({ code: 'ISNER', label: 'John Isner', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAA--A_htGEwQ_96x96.png' }),
  OPELKA: new Equipe({ code: 'OPELKA', label: 'Reilly Opelka', codePays : 'US', url: 'https://ssl.gstatic.com/onebox/media/sports/photos/tennis/AAH9YA_v4EneA_96x96.png' }),
  RUS_ARANTXA: new Equipe({ code: 'RUS_ARANTXA', label: 'Arantxa Rus', codePays : 'US', url: URL_PAYER_INCONNU }),
  KUNG: new Equipe({ code: 'KUNG', label: 'Leonie Kung', codePays : 'SU', url: URL_PAYER_INCONNU }),
  IVASHKA: new Equipe({ code: 'IVASHKA', label: 'Ilya Ivashka', codePays : '', url: URL_PAYER_INCONNU }),
  SHVEDOVA: new Equipe({ code: 'SHVEDOVA', label: 'Yaroslava Shvedova', codePays : '', url: URL_PAYER_INCONNU }),
  GAIO: new Equipe({ code: 'GAIO', label: 'Federico Gaio', codePays : 'IT', url: URL_PAYER_INCONNU }),
  Vilella: new Equipe({ code: 'Vilella', label: 'Mario Vilella Martínez', codePays : 'ES', url: URL_PAYER_INCONNU }),
};

export const CLUBS_FOOTBALL: any = {
  // Autralie
  RB_SALZBURG: new Equipe({ code: 'RB_SALZBURG', label: 'RB Salzburg', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/vQhr4NoE_4Yg1IhUZvbRNw_96x96.png' }),
  RAPID_VIENNE: new Equipe({ code: 'RAPID_VIENNE', label: 'Rapid Vienne', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/ksn7E1QWsnoXRq7vOZkBEA_96x96.png' }),
  LASK: new Equipe({ code: 'LASK', label: 'LASK', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgYwMTAxMDE.png?sig=AI8nk_cKcnR4pQAN2UouVy2idGki&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=gYzYZLTOIdQ&w=96&h=96' }),
  STURM_GRAZ: new Equipe({ code: 'STURM_GRAZ', label: 'Sturm Graz', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/A5aNjxC7AJ2C__lAkU9Plg_96x96.png' }),
  WSG_SWAROVSKI: new Equipe({ code: 'WSG_SWAROVSKI', label: 'WSG Swarovski Tirol', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgA.png?sig=AI8nk_cT_fvF9XHLwmKH9FoQ7l3x&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=TTGMbb7EXmY&w=96&h=96' }),
  WOLFSBERGER: new Equipe({ code: 'WOLFSBERGER', label: 'Wolfsberg', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/y-rIVHO8NpEgB0EtzDrYYA_96x96.png' }),
  AUSTRIA_VIENNE: new Equipe({ code: 'AUSTRIA_VIENNE', label: 'Australia Vienne', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/8OD98qt13JrEFYjRYuxnGw_96x96.png' }),
  HARTBERG: new Equipe({ code: 'HARTBERG', label: 'Hartberg', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgYxZjhlZmI.png?sig=AI8nk_eEGA7E7NdpIShRLsHefo9X&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=mavZyUswq6U&w=96&h=96' }),
  ST_POLTEN: new Equipe({ code: 'ST_POLTEN', label: 'ST Polten', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgYxRDNEQzg.png?sig=AI8nk_ehOTftTAhRLW83Qwv3i9tI&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=NAe57hYHiYE&w=96&h=96' }),
  RIED: new Equipe({ code: 'RIED', label: 'Ried', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgYxNDJjMjU.png?sig=AI8nk_d5XQ0D93LDRgX_8A4n3AUh&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=Q682DSiEklk&w=96&h=96' }),
  RHEINDORF_ALTACH: new Equipe({ code: 'RHEINDORF_ALTACH', label: 'Rheindorf', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgYwMDAwMDA.png?sig=AI8nk_dGt7qwEVp9ek4ARNvpY1gz&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=r7Evjfpq7nk&w=96&h=96' }),
  ADMIRA: new Equipe({ code: 'ADMIRA', label: 'Admira', codePays : 'Admira', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/I4e2Ttjlw1xrZ80Ag_nXQg_96x96.png' }),

  // CHAMPIONSHIP
  NORWICH_CITY: new Equipe({ code: 'NORWICH_CITY', label: 'Norwich City', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/y-we_-8ySOubta5psWzDoA_96x96.png' }),
  WATFORD: new Equipe({ code: 'WATFORD', label: 'Watford', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/lHr1L31i7aJS-O8tUdHOIQ_96x96.png' }),
  BRENTFORD: new Equipe({ code: 'BRENTFORD', label: 'Brentford', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/QOUce0WQBYqnkSmN6_TxGA_96x96.png' }),
  SWANSEA: new Equipe({ code: 'SWANSEA', label: 'Swansea', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/45heVhzL3HvaZW3e2B94kg_96x96.png' }),
  BARNSLEY: new Equipe({ code: 'BARNSLEY', label: 'Barnsley', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/xA0k0rZwCeUA0klmw9n9iQ_96x96.png' }),
  READING: new Equipe({ code: 'READING', label: 'Reading', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/aQoPSirn2zYnaYDn1FTd2Q_96x96.png' }),
  BOURNEMOUTH: new Equipe({ code: 'BOURNEMOUTH', label: 'Bournemouth', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/IcOt-hrK04B-RlRwI3R0yA_96x96.png' }),
  CARDIFF: new Equipe({ code: 'CARDIFF', label: 'Cardiff', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/mTDxrTqWa4SqI0rCi5LhqA_96x96.png' }),
  MILLWALL: new Equipe({ code: 'MILLWALL', label: 'Millwall', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/FjQESJIwYuTRJ5B7HvtzPA_96x96.png' }),
  MIDDLESBROUGH: new Equipe({ code: 'MIDDLESBROUGH', label: 'Middlesbrough', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/tSAATe0_UkCtEX0hgEdyTg_96x96.png' }),
  STOKE_CITY: new Equipe({ code: 'STOKE_CITY', label: 'Stoke City', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/T9sIbS6mr9BuRKY6y4FFLA_96x96.png' }),
  QPR: new Equipe({ code: 'QPR', label: 'QPR', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/SYBiHsr8jq3vT4p0HauolA_96x96.png' }),
  LUTON_TOWN: new Equipe({ code: 'LUTON_TOWN', label: 'Luton Town', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/3e7bXAkZVEVAKQWTRQdGFw_96x96.png' }),
  BRISTOF_CITY: new Equipe({ code: 'BRISTOF_CITY', label: 'Bristof City', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TdB6iSSRKPZ3diEBygOi_A_96x96.png' }),
  NOTTM_FOREST: new Equipe({ code: 'NOTTM_FOREST', label: 'Nottm Forest', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Zr6FbE-8pDH7UBpWCO8U9A_96x96.png' }),
  PRESTON_NORTH_END: new Equipe({ code: 'PRESTON_NORTH_END', label: 'Preston North End', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/2NRxn9AO_zb45mFCRIdCYQ_96x96.png' }),
  BLACKBURN: new Equipe({ code: 'BLACKBURN', label: 'Blackburn', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/9SHzswVb2HlYJfeUEkQNiQ_96x96.png' }),
  DERBY_COUNTY: new Equipe({ code: 'DERBY_COUNTY', label: 'Derby Country', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/PvtlG2gQHu9CD8NvqJWTXA_96x96.png' }),
  HUDDERSFIELD: new Equipe({ code: 'HUDDERSFIELD', label: 'Huddersfield', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Pkhtbw1Npp_vEjxqRSZWwA_96x96.png' }),
  COVENTRY_CITY: new Equipe({ code: 'COVENTRY_CITY', label: 'Coventry City', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/KHpmY4tIwqiutl8Cfl0MAw_96x96.png' }),
  BIRMINGHAM: new Equipe({ code: 'BIRMINGHAM', label: 'Birmingham', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/vZkXVHm56WFEs_I5q9OnJQ_96x96.png' }),
  ROTHERHAM: new Equipe({ code: 'ROTHERHAM', label: 'Rotherham', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/qdyrslqZJUKii5W44EpqLQ_96x96.png' }),
  SHEFFIELD: new Equipe({ code: 'SHEFFIELD', label: 'Sheffield Wednesday', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/9HNkxC3WNDFrs4XEWbkOrQ_96x96.png' }),
  WYCOMBE: new Equipe({ code: 'WYCOMBE', label: 'Wycombe', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/1aoG8QFXG9lm0inYUg-YAg_96x96.png' }),

  // LIGUE 1 FR
  ANGERS: new Equipe({ code: 'ANGERS', label: 'Angers', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/I4e2Ttjlw1xrZ80Ag_nXQg_96x96.png' }),
  BORDEAUX: new Equipe({ code: 'BORDEAUX', label: 'Bordeaux', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/K-yrHqlMCFB4sT9DSlcHIQ_96x96.png' }),
  BREST: new Equipe({ code: 'BREST', label: 'Brest', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/HNqZwlu71GHXo60XjYrPxg_96x96.png' }),
  DIJON: new Equipe({ code: 'DIJON', label: 'Dijon', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Qf3Beb1hzy-ENYzJOSVJ0Q_96x96.png' }),
  LENS: new Equipe({ code: 'LENS', label: 'Lens', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TUvwItKazVFpgThEhhlN1Q_96x96.png' }),
  LILLE: new Equipe({ code: 'LILLE', label: 'Lille', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/D2AQe8qoyPIP4K8MzLvwuA_96x96.png' }),
  LORIENT: new Equipe({ code: 'LORIENT', label: 'Lorient', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/bbYkAWWtD6lpK5KyGfr1vA_96x96.png' }),
  METZ: new Equipe({ code: 'METZ', label: 'Metz', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/pKiX1s6Rr8IxVQCuwIKKpg_96x96.png' }),
  MONACO: new Equipe({ code: 'MONACO', label: 'Monaco', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/svD-B0kpoDlKfZuiJxMs4Q_96x96.png' }),
  MONTPELIER: new Equipe({ code: 'MONTPELIER', label: 'Montpelier', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/fL5Nk_2eUanYiOSB9AnBpQ_96x96.png' }),
  NANTES: new Equipe({ code: 'NANTES', label: 'Nantes', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/r3qizrAtoAXPICgYjFYCyA_96x96.png' }),
  NICE: new Equipe({ code: 'NICE', label: 'Nice', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Llrxrqsc3Tw4JzE6xM7GWw_96x96.png' }),
  NIMES: new Equipe({ code: 'NIMES', label: 'Nîmes', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/PxMdAScr1phMfc-IN8JYcg_96x96.png' }),
  LYON: new Equipe({ code: 'LYON', label: 'Lyon', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/SrKK55dUkCxe4mJsyshfCg_96x96.png' }),
  MARSEILLE: new Equipe({ code: 'MARSEILLE', label: 'Marseille', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/KfBX1kHNj26r9NxpqNaTkA_96x96.png' }),
  PARIS_SG: new Equipe({ code: 'PARIS_SG', label: 'Paris-SG', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/mcpMspef1hwHwi9qrfp4YQ_96x96.png' }),
  REIMS: new Equipe({ code: 'LENS', label: 'Reims', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/BL07y-EwrviKRTK1y00l7g_96x96.png' }),
  RENNES: new Equipe({ code: 'RENNES', label: 'Rennes', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/guI8eg4hoTyIp6rO1opjxA_96x96.png' }),
  ST_ETIENNE: new Equipe({ code: 'ST_ETIENNE', label: 'Saint-Etienne', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/k-EMFQteFMhhnEWVch_dBA_96x96.png' }),
  STRASBOURG: new Equipe({ code: 'STRASBOURG', label: 'Strasbourg', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Eb9xtMpUy8FXQ0RCKvLxcg_96x96.png' }),
  PAU_FC: new Equipe({ code: 'PAU_FC', label: 'Pau PC', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/8tjPEm0_7YNsViRVZEedmg_96x96.png' }),

  // LIGUE 2 FR
  SOCHAUX: new Equipe({ code: 'SOCHAUX', label: 'Sochaux', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/wWvPrYkUfTFWGg7ZAHmpPg_96x96.png' }),
  AUXERRE: new Equipe({ code: 'AUXERRE', label: 'Auxerre', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/jX0oM3wnm6cWOGKoUR3AyA_96x96.png' }),
  TOULOUSE: new Equipe({ code: 'TOULOUSE', label: 'Toulouse', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/MfN3W9gXcHgRDAYCv-M5Dw_96x96.png' }),
  AJACCIO: new Equipe({ code: 'AJACCIO', label: 'Ajaccio', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/7PC7epWhG1IPz4ypx1QS2w_96x96.png' }),
  CAEN: new Equipe({ code: 'CAEN', label: 'Caen', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/NnHgkdbf-NLhwO83FKo1bg_96x96.png' }),
  GUINGAMP: new Equipe({ code: 'GUINGAMP', label: 'Guingamp', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/XQv_Ulysoyap0FzOPUA-mA_96x96.png' }),
  AMIENS: new Equipe({ code: 'AMIENS', label: 'Amiens', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/7tIMJ9c8ziM74zLlp7Xm6Q_96x96.png' }),
  NIORT: new Equipe({ code: 'NIORT', label: 'Niort', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TXjieB5nxtAKiD6Xassg7g_96x96.png' }),
  NANCY: new Equipe({ code: 'NANCY', label: 'Nancy', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/MHlgXPd6_jt7JS_KkGfD5w_96x96.png' }),
  LE_HAVRE: new Equipe({ code: 'LE_HAVRE', label: 'Le Havre', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/BRitaBE1_mjMJguk6xzTRw_96x96.png' }),
  CHATEAUROUX: new Equipe({ code: 'CHATEAUROUX', label: 'Châteauroux', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/3931g3VJkxGEEbkYr6Ip5A_96x96.png' }),
  TROYES: new Equipe({ code: 'TROYES', label: 'Troyes', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/BUjNnbc4kDTOc5I0IzOQog_96x96.png' }),
  CLERMONT: new Equipe({ code: 'CLERMONT', label: 'Clermont', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/0aur9jOW37pq6dUzu61wWQ_96x96.png' }),
  GRENOBLE: new Equipe({ code: 'GRENOBLE', label: 'Grenoble', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/2v8NWuMbu3txvONnDm1jaA_96x96.png' }),
  VALENCIENNES: new Equipe({ code: 'VALENCIENNES', label: 'Valenciennes', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/hJOupTlPOOiRx3w-XMO3hg_96x96.png' }),
  PARIS_FC: new Equipe({ code: 'PARIS_FC', label: 'Paris FC', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/6L0HPrdS4FdFbafBX80QuQ_96x96.png' }),
  RODEZ: new Equipe({ code: 'RODEZ', label: 'Rodez', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/seB78PSR2RZcg6-Jb7snsA_96x96.png' }),
  USL_DUNKERQUE: new Equipe({ code: 'USL_DUNKERQUE', label: 'USL Dunkerque', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgA.png?sig=AI8nk_cT_fvF9XHLwmKH9FoQ7l3x&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=TTGMbb7EXmY&w=96&h=96' }),
  CHAMBLY: new Equipe({ code: 'CHAMBLY', label: 'Chambly', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/DiPjRtIHOkWK0JQNYVAUlg_96x96.png' }),

  // Autres
  FC_BRUGES: new Equipe({ code: 'FC_BRUGES', label: 'FC Bruges', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/5FQBXpID1LAQJb0BOnmTpw_96x96.png' }),
  GALATASARAY: new Equipe({ code: 'GALATASARAY', label: 'Galatasaray', codePays : 'TU', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TWjoccvTU4JXZJZ3aW3cVg_96x96.png' }),
  ISTANBUL_BASAKSEHIR: new Equipe({ code: 'ISTANBUL_BASAKSEHIR', label: 'Istanbul Basaksehir', codePays : 'TU', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/b_G6FYhPyTa_WdhdikiqyA_96x96.png' }),

  AZ_ALKMAAR: new Equipe({ code: 'AZ_ALKMAAR', label: 'AZ Alkmaar', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Lhhh1mbsrqH2K1AfXFazrQ_96x96.png' }),
  ANGLETERRE: new Equipe({ code: 'ANGLETERRE', label: 'Angleterre', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/DTqIL8Ba3KIuxGkpXw5ayA_96x96.png' }),
  PAYS_DE_GALLES: new Equipe({ code: 'PAYS_DE_GALLES', label: 'Pays de Galles', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/1JjnDm6Es30LryHzbudyEw_96x96.png' }),
  FRANCE: new Equipe({ code: 'FRANCE', label: 'France', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/z3JEQB3coEAGLCJBEUzQ2A_96x96.png' }),
  PORTUGAL: new Equipe({ code: 'PORTUGAL', label: 'Portugal', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/HJ3_2c4w791nZJj7n-Lj3Q_96x96.png' }),
  POLOGNE: new Equipe({ code: 'POLOGNE', label: 'Pologne', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/yTS_Piy3M1wUBnqU0n5aAw_96x96.png' }),
  ITALIE: new Equipe({ code: 'ITALIE', label: 'Italie', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/joYpsiaYi4GDCqhSRAq5Zg_96x96.png' }),
  UKRAINE: new Equipe({ code: 'UKRAINE', label: 'Ukraine', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/DQIQtK7N4yrDIqw75pxFHg_96x96.png' }),
  MIDTJYLLAND: new Equipe({ code: 'MIDTJYLLAND', label: 'Midtjylland', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/dEMzZJoIUS2CdquWiHjR3A_96x96.png' }),
  OLYMPIAKOS: new Equipe({ code: 'OLYMPIAKOS', label: 'Olympiakos', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/FqnQ9nu7UDiSgnXKohdIgg_96x96.png' }),
  MOLDE: new Equipe({ code: 'MOLDE', label: 'Molde', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/rtZHldVypISZPjUeVsEcSg_96x96.png' }),
  SPARTA_PRAGUE: new Equipe({ code: 'SPARTA_PRAGUE', label: 'Sparta Prague', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/enJq_hTBvjkLwzIFRyvREw_96x96.png' }),
  CSKA_SOFIA: new Equipe({ code: 'CSKA_SOFIA', label: 'CSKA Sofia', codePays : 'FR', url: 'https://dimg-pa.googleapis.com/lg/CgZlYTFjMjQ.png?sig=AI8nk_cOD2dRTSamLIf6gjHBGXQ_&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=7wNH_khzAXk&w=96&h=96' }),
  YOUNG_BOYS: new Equipe({ code: 'YOUNG_BOYS', label: 'Young Boys', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/PxDppOF513PSruqWNIIE2w_96x96.png' }),
  SUEDE: new Equipe({ code: 'SUEDE', label: 'Suede', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/OkFlRvRsKMWb8Hk20L9Trw_96x96.png' }),

  // PREMIERE LEGAUE
  LIVERPOOL: new Equipe({ code: 'LIVERPOOL', label: 'Liverpool', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/0iShHhASp5q1SL4JhtwJiw_96x96.png' }),
  LEICESTER: new Equipe({ code: 'LEICESTER', label: 'Leicester', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/UDYY4FSlty6fXFBzvFfcyw_96x96.png' }),
  TOTTENHAM: new Equipe({ code: 'TOTTENHAM', label: 'Tottenham', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/k3Q_mKE98Dnohrcea0JFgQ_96x96.png' }),
  MANCHESTER_UNITED: new Equipe({ code: 'MANCHESTER_UNITED', label: 'Manchester United', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/udQ6ns69PctCv143h-GeYw_96x96.png' }),
  EVERTON: new Equipe({ code: 'EVERTON', label: 'Everton', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/C3J47ea36cMBc4XPbp9aaA_96x96.png' }),
  MAN_CITY: new Equipe({ code: 'MAN_CITY', label: 'Manchester City', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/z44l-a0W1v5FmgPnemV6Xw_96x96.png' }),
  CHELSEA: new Equipe({ code: 'CHELSEA', label: 'Chelsea', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/fhBITrIlbQxhVB6IjxUO6Q_96x96.png' }),
  ASTON_VILLA: new Equipe({ code: 'ASTON_VILLA', label: 'Aston Villa', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/uyNNelfnFvCEnsLrUL-j2Q_96x96.png' }),
  WEST_HAM: new Equipe({ code: 'WEST_HAM', label: 'West Ham', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/bXkiyIzsbDip3x2FFcUU3A_96x96.png' }),
  WOLVERHAMPTION: new Equipe({ code: 'WOLVERHAMPTION', label: 'Wolverhampton', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/-WjHLbBIQO9xE2e2MW3OPQ_96x96.png' }),
  NEWCASTLE: new Equipe({ code: 'NEWCASTLE', label: 'Newcastle', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/96CcNNQ0AYDAbssP0V9LuQ_96x96.png' }),
  CRYSTAL_PALACE: new Equipe({ code: 'BURNLEY', label: 'Burley', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/8piQOzndGmApKYTcvyN9vA_96x96.png' }),
  BURNLEY: new Equipe({ code: 'BURNLEY', label: 'Burley', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/teLLSaMXim_8BA1d93sMng_96x96.png' }),
  SOUTHAMPTON: new Equipe({ code: 'SOUTHAMPTON', label: 'Southampton', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/y1V4sm2SEBiWUPRIYl5rfg_96x96.png' }),
  LEEDS_UNITED: new Equipe({ code: 'LEEDS_UNITED', label: 'Leeds United', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/5dqfOKpjjW6EwTAx_FysKQ_96x96.png' }),
  ARSENAL: new Equipe({ code: 'ARSENAL', label: 'Arsenal', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/4us2nCgl6kgZc0t3hpW75Q_96x96.png' }),
  BRIGHTON: new Equipe({ code: 'BRIGHTON', label: 'Brighton', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/EKIe0e-ZIphOcfQAwsuEEQ_96x96.png' }),
  FULLHAM: new Equipe({ code: 'FULLHAM', label: 'Fullham', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Gh7_5p3n364p4vxeM8FhNg_96x96.png' }),
  WBA: new Equipe({ code: 'WBA', label: 'WBA', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Im2UqFKvfm3TaM7R2RYkjw_96x96.png' }),
  SHEFFIELD_UTD: new Equipe({ code: 'SHEFFIELD_UTD', label: 'Sheffield United', codePays : 'EN', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/wF8AgQsssfy3_GLyVR3dSg_96x96.png' }),

  // ESPAGNE
  ATLETICO_MADRID: new Equipe({ code: 'ATLETICO_MADRID', label: 'Atletico Madrid', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/srAAE0bOnCppUrlbJpFiHQ_96x96.png' }),
  REAL: new Equipe({ code: 'REAL', label: 'Real Madrid', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Th4fAVAZeCJWRcKoLW7koA_96x96.png' }),
  REAL_SOCIEDAD: new Equipe({ code: 'REAL_SOCIEDAD', label: 'Real Sociedad', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/w8tb1aeBfVZIj9tZXf7eZg_96x96.png' }),
  VILLARREAL: new Equipe({ code: 'VILLARREAL', label: 'Villarreal', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/WKH7Ak5cYD6Qm1EEqXzmVw_96x96.png' }),
  BARCELONE: new Equipe({ code: 'BARCELONE', label: 'Barcelona', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/paYnEE8hcrP96neHRNofhQ_96x96.png' }),
  GRENADE: new Equipe({ code: 'GRENADE', label: 'Grenade', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Fn_X2IO4-1ACuTemcHkDEw_96x96.png' }),
  SEVILLE: new Equipe({ code: 'SEVILLE', label: 'FC Seville', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/hCTs5EX3WjCMC5Jl3QE4Rw_96x96.png' }),
  CELTA_VIGO: new Equipe({ code: 'CELTA_VIGO', label: 'Celta Vigo', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/wpdhixHP_sloegfP0UlwAw_96x96.png' }),
  CADIX: new Equipe({ code: 'CADIX', label: 'Cadix', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/H1vdTrUUqJBeUW1HfbW0nQ_96x96.png' }),
  ATH_BILBAO: new Equipe({ code: 'ATH_BILBAO', label: 'Ath. Bilbao', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/OSL_5Zm6kYPP1J17Bo5uDA_96x96.png' }),
  GETAFE: new Equipe({ code: 'GETAFE', label: 'Getafe', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/1UDHZMdKZD15W5gus7dJyg_96x96.png' }),
  BETIS: new Equipe({ code: 'BETIS', label: 'Betis', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/S0fDZjYYytbZaUt0f3cIhg_96x96.png' }),
  VALENCE: new Equipe({ code: 'VALENCE', label: 'Valence', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/QPbjvDwI_0Wuu4tCS2O6uw_96x96.png' }),
  EIBAR: new Equipe({ code: 'EIBAR', label: 'Eibar', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/sbTFnFgPeUsTa-szphHf8Q_96x96.png' }),
  LEVANTE: new Equipe({ code: 'LEVANTE', label: 'Levante', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/SQB-jlVosxVV1Ce79FhbOA_96x96.png' }),
  ELCHE: new Equipe({ code: 'ELCHE', label: 'Elche', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/uyyqqxLIYT_lQIXRyMI_RA_96x96.png' }),
  DEPORTIVO_ALA: new Equipe({ code: 'DEPORTIVO_ALA', label: 'Deportivo Alaves', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/meAnutdPID67rfUecKaoFg_96x96.png' }),
  VALLADOLID: new Equipe({ code: 'VALLADOLID', label: 'Valladolid', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/HlIrXZRP96tv0H1uiiN0Jg_96x96.png' }),
  HUESCA: new Equipe({ code: 'HUESCA', label: 'Huesca', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/S72MCTiOGlQRhTfHW0uf9A_96x96.png' }),
  OSASUNA: new Equipe({ code: 'OSASUNA', label: 'Osasuna', codePays : 'ES', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/pk-hNCNpGM_JDoHHvLVF-Q_96x96.png' }),

  // Bundesliga
  BAYER_LEVERKUSEN: new Equipe({ code: 'BAYER_LEVERKUSEN', label: 'Bayer Leverkusen', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/0zIcXiwD_JGY482DFC28Lw_96x96.png' }),
  BAYERN: new Equipe({ code: 'BAYERN', label: 'Bayern', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/-_cmntP5q_pHL7g5LfkRiw_96x96.png' }),
  RB_LEIPZIG: new Equipe({ code: 'RB_LEIPZIG', label: 'RB Leipzig', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/R7-Lqc_SDxd97uWgoeUQ-g_96x96.png' }),
  WOLFSBOURG: new Equipe({ code: 'WOLFSBOURG', label: 'Wolfsbourg', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/nCdwmPlnAA041M4HDMzmkg_96x96.png' }),
  DORTMUND: new Equipe({ code: 'DORTMUND', label: 'Dortmund', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/FZnTSH2rbHFos4BnlWAItw_96x96.png' }),
  UNION_BERLIN: new Equipe({ code: 'UNION_BERLIN', label: 'Union Berlin', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/zsPvbWQ2kNoiZX3sZXq-Yg_96x96.png' }),
  STUTTGART: new Equipe({ code: 'STUTTGART', label: 'Stuttgart', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Qc_eb6-lZEDR8ojQmZxFhQ_96x96.png' }),
  MONCHNGLADBACH: new Equipe({ code: 'MONCHNGLADBACH', label: 'Monchngladbach', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/HFg_gp-vbuL7z1Othoa0ZA_96x96.png' }),
  EINTRACHT: new Equipe({ code: 'EINTRACHT', label: 'Eintracht', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/VOizBJPDHnvnSaU3XPVGAw_96x96.png' }),
  FRIBOURG: new Equipe({ code: 'FRIBOURG', label: 'Fribourg', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/s0YO0sK9qrioMnzJuFGKuw_96x96.png' }),
  AUGSBOURG: new Equipe({ code: 'AUGSBOURG', label: 'Augsbourg', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/gjz1Ml0qpVQuY3leN4z8mQ_96x96.png' }),
  HOFFENHEIN: new Equipe({ code: 'HOFFENHEIN', label: 'Hoffenhein', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/zlO6wgTW2QB30eOypHGxDg_96x96.png' }),
  WERDER: new Equipe({ code: 'WERDER', label: 'Werder', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/v4G9srMr-9IWDhCXiPhAIw_96x96.png' }),
  HERTHA_BSC: new Equipe({ code: 'HERTHA_BSC', label: 'Hertha BSC', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/PQMb_rQTIwV-OOhkwHN3qA_96x96.png' }),
  COLOGNE: new Equipe({ code: 'COLOGNE', label: 'Cologne', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/W94hx-q1SdXOZBrW6RSSVg_96x96.png' }),
  ARMINIA: new Equipe({ code: 'ARMINIA', label: 'Arminia Bielefeld', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/_qX-fvMs2zUBxfmbj233xw_96x96.png' }),
  MAINZ_05: new Equipe({ code: 'MAINZ_05', label: 'Mainz 05', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/-_DNuqGrrFQ5FUvKjb7zAw_96x96.png' }),
  SCHALKE: new Equipe({ code: 'SCHALKE', label: 'Schalke', codePays : 'AL', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/3CjFxnIvrHJ1-pJq6B5ZQw_96x96.png' }),

  // ITALIE
  MILAN: new Equipe({ code: 'MILAN', label: 'Milan', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/VoKsJ6RitaHGhsM62e6AXQ_96x96.png' }),
  INTER: new Equipe({ code: 'INTER', label: 'Inter', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/gpWqqaYc9yESzfkfspryoA_96x96.png' }),
  ROMA: new Equipe({ code: 'ROMA', label: 'Roma', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/BQdP4jUBFJfG7U_JBsFIMg_96x96.png' }),
  SASSUOLO: new Equipe({ code: 'SASSUOLO', label: 'Sassuolo', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/GoeTFIVAZLA5JWk0-A6B0A_96x96.png' }),
  NAPLES: new Equipe({ code: 'NAPLES', label: 'Naples', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/PWRLYBJqlGrAAsKkUN6eng_96x96.png' }),
  JUVENTUS: new Equipe({ code: 'JUVENTUS', label: 'Juventus', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Lv6xmBlUIpN3GAFhtf6nqQ_96x96.png' }),
  ATALANTA: new Equipe({ code: 'ATALANTA', label: 'Atlanta United FC', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/0XmrZHobvb6ua5tgMOnTEA_96x96.png' }),
  LAZIO: new Equipe({ code: 'LAZIO', label: 'Lazio', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/jcKKlUVaNw3br9cIyOKmQA_96x96.png' }),
  HELLAS_VERONE: new Equipe({ code: 'HELLAS_VERONE', label: 'Hellas Verone', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Y23PEIJgTvK3Qpm9il1MGA_96x96.png' }),
  BENEVENT: new Equipe({ code: 'BENEVENT', label: 'Benevent', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/LyjvhG7wXe-iVAepsbjIVg_96x96.png' }),
  SAMPDORIA: new Equipe({ code: 'SAMPDORIA', label: 'Sampdoria', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/E8bC8MBR8FwSP3ONEhMxjw_96x96.png' }),
  UDINESE: new Equipe({ code: 'UDINESE', label: 'Unidese', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/92Aw_iasBENKmzvdpbTpHQ_96x96.png' }),
  FIORENTINA: new Equipe({ code: 'FIORENTINA', label: 'Fiorentina', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/5BhAG7vGRyQLIXtfMG3L2Q_96x96.png' }),
  CAGLIARI: new Equipe({ code: 'CAGLIARI', label: 'Cagliari', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/e9XfySyGdfyJ4UzEkYwENw_96x96.png' }),
  PARME: new Equipe({ code: 'PARME', label: 'Parme', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Pr7ZXZlx34eEXdUMTkLvkw_96x96.png' }),
  SPEZIA: new Equipe({ code: 'SPEZIA', label: 'Spezia', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/UzdHN3YGjZDZGfSMQuZrYw_96x96.png' }),
  CALCIO: new Equipe({ code: 'CALCIO', label: 'Spezia', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/UzdHN3YGjZDZGfSMQuZrYw_96x96.png' }),
  GENOA: new Equipe({ code: 'GENOA', label: 'Genoa', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/GlyoZO04xkwVX6oTh8asHA_96x96.png' }),
  CROTONE: new Equipe({ code: 'CROTONE', label: 'Crotone', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/SJTkRPiSPKkhhMcMm_DVSQ_96x96.png' }),
  TORINO: new Equipe({ code: 'TORINO', label: 'Torino', codePays : 'IT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/ovE3HSEx4GWXkW8GU7KVhA_96x96.png' }),

  // PORTUGAL
  SPORTING: new Equipe({ code: 'SPORTING', label: 'Sporting', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/58doDuhR0wW3WZE9PdODUw_96x96.png' }),
  BENFICA: new Equipe({ code: 'BENFICA', label: 'Benfica', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TnVPpMgpue_Vz_30C2HAPA_96x96.png' }),
  PORTO: new Equipe({ code: 'PORTO', label: 'Porto', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/QkkllEKwkj60jEVtOEZWAg_96x96.png' }),
  BRAGA: new Equipe({ code: 'BRAGA', label: 'Braga', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/1orTeFljffloKztScEN2RA_96x96.png' }),
  GUIMARAES: new Equipe({ code: 'GUIMARAES', label: 'Guimaraes', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/UkXfMrlrgYiUhK91JaKwYw_96x96.png' }),
  PACOS_FERREIRA: new Equipe({ code: 'PACOS_FERREIRA', label: 'Paços Ferreira', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TN_EXYEUzpVi-q9GM2mVZw_96x96.png' }),
  SANTA_CLARA: new Equipe({ code: 'SANTA_CLARA', label: 'Santa Clara', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/i0cKD3neXF2M09arqLQO5g_96x96.png' }),
  CD_NACIONAL: new Equipe({ code: 'CD_NACIONAL', label: 'CD Nacional', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/qyy50QMMYekML4pWPjLJkw_96x96.png' }),
  GIL_VICENTE: new Equipe({ code: 'GIL_VICENTE', label: 'Gil Vicente', codePays : 'PT', url: 'https://dimg-pa.googleapis.com/lg/CgZjYzAwMDA.png?sig=AI8nk_ddX5IT7F2koVHuWHUTqRRQ&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=qlkzLuu4bJU&w=96&h=96' }),
  FAMALICAO: new Equipe({ code: 'FAMALICAO', label: 'Famalicao', codePays : 'PT', url: 'https://dimg-pa.googleapis.com/lg/CgA.png?sig=AI8nk_cT_fvF9XHLwmKH9FoQ7l3x&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=TTGMbb7EXmY&w=96&h=96' }),
  RIO_AVE: new Equipe({ code: 'RIO_AVE', label: 'Rio Ave', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/VG25vxdw0DTdTD_MIiil-Q_96x96.png' }),
  BELENENSES: new Equipe({ code: 'BELENENSES', label: 'Belenenses', codePays : 'PT', url: 'https://dimg-pa.googleapis.com/lg/CgA.png?sig=AI8nk_cT_fvF9XHLwmKH9FoQ7l3x&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=TTGMbb7EXmY&w=96&h=96' }),
  MOREIRENSE: new Equipe({ code: 'MOREIRENSE', label: 'Moreirense', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/GVi9CQNTfywAlEId1LI9-A_96x96.png' }),
  MARITIMO: new Equipe({ code: 'MARITIMO', label: 'Maritimo', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/L4mOC2px5No8NzSvXAmUpw_96x96.png' }),
  FARENSE: new Equipe({ code: 'FARENSE', label: 'Farense', codePays : 'PT', url: 'https://dimg-pa.googleapis.com/lg/CgA.png?sig=AI8nk_cT_fvF9XHLwmKH9FoQ7l3x&key=AIzaSyCUqbG5Kw_8jb3cy2ZBKvV2kAi8z0qmQO0&sk=TTGMbb7EXmY&w=96&h=96' }),
  BAOVISTA: new Equipe({ code: 'BAOVISTA', label: 'Boavista', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/By55z84mN_FMRPKVlqZiSA_96x96.png' }),
  TONDELA: new Equipe({ code: 'TONDELA', label: 'Tondela', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/zcWLW2uxBO_juVh-TA65EQ_96x96.png' }),
  PORIMINENSE: new Equipe({ code: 'PORIMINENSE', label: 'Poriminense', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/hcJq-0yiPpDIZ5OOGo8mVg_96x96.png' }),
  // INTER: new Equipe({ code: '', label: '', codePays : 'PT', url: '' }),
  // INTER: new Equipe({ code: '', label: '', codePays : 'PT', url: '' }),

  // SCOTTICH PREMIERSHIP
  RANGERS: new Equipe({ code: 'RANGERS', label: 'Rangers', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/VJtO19cqg-zp3wuDuOwqAg_96x96.png' }),
  CELTIC: new Equipe({ code: 'CELTIC', label: 'Celtic', codePays : 'FR', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/2d1R7XIFALAHj2A9ECBJeA_96x96.png' }),
  HIBERNIAN: new Equipe({ code: 'HIBERNIAN', label: 'Hibernian', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Ta29ZyjXNsYipTnah-giSw_96x96.png' }),
  ABERDEEN: new Equipe({ code: 'ABERDEEN', label: 'Aberdeen', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/28jiCmg0exED6EdjQ8uo5Q_96x96.png' }),
  LIVINGSTON: new Equipe({ code: 'LIVINGSTON', label: 'Livingston', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/IDhi6jZT6y_O2Nc7kbuaLQ_96x96.png' }),
  ST_MIRREN: new Equipe({ code: 'ST_MIRREN', label: 'ST Mirren', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/SuOGznWJXmTn6HRBJZ5X2A_96x96.png' }),
  DUNDEE_UNITED: new Equipe({ code: 'DUNDEE_UNITED', label: 'Dundee United', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/ASZy-PyWma-FqRbSRcnd2Q_96x96.png' }),
  ST_JOHNSTONE: new Equipe({ code: 'ST_JOHNSTONE', label: 'ST Johnstone', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/O3YcYWnW8NjTXBhF5vASEA_96x96.png' }),
  MOTHERWELL: new Equipe({ code: 'MOTHERWELL', label: 'Motherwell', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/R2DuIbFzehS5OSrqUx2-og_96x96.png' }),
  KILMARNOCK: new Equipe({ code: 'KILMARNOCK', label: 'Kilmarnock', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TyMo1NQpDKAPM6cYYpUUjw_96x96.png' }),
  HAMILTON: new Equipe({ code: 'HAMILTON', label: 'Hamilton', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Ch_0e0dhuFXkgKROOF8F9A_96x96.png' }),
  ROSS_COUNTRY: new Equipe({ code: 'ROSS_COUNTRY', label: 'Ross country', codePays : 'PT', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/yhoJzLSKHOGmQhZMLXOUPA_96x96.png' })
};



export const CLUBS_HOCHEY_GLACE: any = {
  PANTHERS: new Equipe({ code: 'PANTHERS', label: 'Panthers', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/HhkdL7JKqdlVy_DtjLOjbw_96x96.png' }),
  MAPLE_LEAFS: new Equipe({ code: 'MAPLE_LEAFS', label: 'Maple Leafs', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/jMSyNOMdJPjHwsmbWukUag_96x96.png' }),
  LIGHTNING: new Equipe({ code: 'LIGHTNING', label: 'Lightning', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/IFjTMxl-nMxMJK2b64xLFQ_96x96.png' }),
  BRUINS: new Equipe({ code: 'BRUINS', label: 'Bruins', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/_KkOxoGjAn3S7_9-Z1d0OA_96x96.png' }),
  SABRES: new Equipe({ code: 'SABRES', label: 'Sabres', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/6vSZsDaiDt1MW__o_ksW4A_96x96.png' }),
  RED_WINGS: new Equipe({ code: 'RED_WINGS', label: 'Red Wings', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/QaP8buCif1FvjfqApkxsDg_96x96.png' }),
  SENATEURS: new Equipe({ code: 'SENATEURS', label: `Sénateurs`, codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/_rlImUQJkjVKGTj1Xkdaaw_96x96.png' }),
  CANADIENS: new Equipe({ code: 'CANADIENS', label: 'Canadiens', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/fhexjWXZM7Sgvd22nDkBOA_96x96.png' }),
  HURRICANES: new Equipe({ code: 'HURRICANES', label: 'Hurricanes', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/nC8dMKdf-zPF4cWq_wSKHA_96x96.png' }),
  RANGERS: new Equipe({ code: 'RANGERS', label: 'Rangers', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/xAan1UsViSOex0EoBJEMOA_96x96.png' }),
  PENGUINS: new Equipe({ code: 'PENGUINS', label: 'Penguins', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/mTXURxq0CbsVREw9q3UAnw_96x96.png' }),
  ISLANDERS: new Equipe({ code: 'ISLANDERS', label: 'Islanders', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/wIWMfokR7qsGJM1gFhRrUA_96x96.png' }),
  BLUE_JACKETS: new Equipe({ code: 'BLUE_JACKETS', label: 'Blue Jackets', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/7lrK9CX_nZj_veEeleHTmg_96x96.png' }),
  DEVILS: new Equipe({ code: 'DEVILS', label: 'Devils', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/dlm2PLEGHJY8DzDLloxLcQ_96x96.png' }),
  FLYERS: new Equipe({ code: 'FLYERS', label: 'Flyers', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/ZFZEyofJ8vMrr0tFGsMFKg_96x96.png' }),
  CAPITALS: new Equipe({ code: 'CAPITALS', label: 'Capitals', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/uT-r__4aRFZmtEITN9mNdQ_96x96.png' }),

  AVALANCHE: new Equipe({ code: 'AVALANCHE', label: 'Avalanche', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/iBFLyMGpOW2Fh5j8s7kYpw_96x96.png' }),
  WILD: new Equipe({ code: 'WILD', label: 'Wild', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/2AkZ-bLhHUaPoj_LlLPBVA_96x96.png' }),
  BLUES: new Equipe({ code: 'BLUES', label: 'Blues', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/oUzPuWuhgzayhHwucx8htQ_96x96.png' }),
  STARS: new Equipe({ code: 'STARS', label: 'Stars', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/yAPda2I1VV6sr0TB17rnxQ_96x96.png' }),
  PREDATORS: new Equipe({ code: 'PREDATORS', label: 'Predators', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/8aNIxgSUNttfOeojBie04w_96x96.png' }),
  JETS: new Equipe({ code: 'JETS', label: 'Jets', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/G92uFvMADMSGFV07IgpUIQ_96x96.png' }),
  BLACKHAWKS: new Equipe({ code: 'BLACKHAWKS', label: 'Blackhawks', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/kUlSd6LbUN7Jj03mqZcgAw_96x96.png' }),
  COYOTES: new Equipe({ code: 'COYOTES', label: 'Coyotes', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/dhQ15Ly2gTPvCPbJEq-OHA_96x96.png' }),

  FLAMES: new Equipe({ code: 'FLAMES', label: 'Flames', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/jwG6UfooGEJ_nvOVT_0ykw_96x96.png' }),
  OILERS: new Equipe({ code: 'OILERS', label: 'Oilers', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/GFR5_nXarHj6qRI8R05otg_96x96.png' }),
  KINGS: new Equipe({ code: 'KINGS', label: 'Kings', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/74fKqDZ5DMq7qup120TeSQ_96x96.png' }),
  GOLDEN_KNIGHTS: new Equipe({ code: 'GOLDEN_KNIGHTS', label: 'Golden Knights', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/QeG0x42j0YlJGYEAwowewA_96x96.png' }),
  CANUCKS: new Equipe({ code: 'CANUCKS', label: 'Canucks', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/1SVoPsK2xW65VIfyQB2soQ_96x96.png' }),
  SHARKS: new Equipe({ code: 'SHARKS', label: 'Sharks', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/TuRBhY0zNhgZUbHQS4VUhQ_96x96.png' }),
  DUCKS: new Equipe({ code: 'DUCKS', label: 'Ducks', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/Ujlge7BWmyIJvsCwu3y-Lw_96x96.png' }),
  KRAKEN: new Equipe({ code: 'KRAKEN', label: 'Kraken', codePays : '', url: 'https://ssl.gstatic.com/onebox/media/sports/logos/gv_klUIk7LBmA857rbdOvw_96x96.png' }),

}
 // PANTHERS: new Equipe({ code: '', label: '', codePays : '', url: '' })
